README.md, etc/install_osx.sh, vmbuild/Makefile
For issue #319. Introduced [homebrew](https://brew.sh) as dependency. It will now install llvm with brew, and use the clang/clang++ compiler from that installation. Also includes some cleanup inside script, and changes to reflect the changes made in `src/Makefile` (CC => CC_INC)
=> Added llvm to install_osx script

.gitignore, README.md, Vagrantfile, etc/install_from_bundle.sh, seed/run.sh
These commits also fix two minor snags I encountered while setting up IncludeOS for the first time.
=> Use Vagrant to standardize build environment

etc/vboxrun.sh
vboxrun.sh only converted the .img to .vdi if .vdi didn't exist. To update your VM with the changes from your service you had to first remove the .vdi, even if the .img (service) had changed.
The script will now remove the .vdi if it already exists, and always convert a new .vdi from .img.
=> vbox script replaces disk so changes gets updated in VM

etc/install_build_only.sh
This script is needed to install the IncludeOS build environment without any runtime tools, such as qemu. This is useful for building docker images.
=> New install script that only downloads and installs bundle, not qemu

api/hw/dev.hpp, api/kernel/pci_manager.hpp, src/kernel/os.cpp, src/kernel/pci_manager.cpp
The pci_manager doesn't represent a hardware component but just
manages pci_devices. Besides, the source file pci_manager.cpp
was already in the src/kernel folder.
=> pci_manager.hpp moved from api/hw to api/kernel

api/hw/disk.hpp, api/hw/ide.hpp, api/hw/ioport.hpp, src/Makefile, src/hw/ide.cpp, test/disks/Makefile, test/disks/debug/service.gdb, test/disks/run.sh, test/disks/service.cpp
Hi, I just have a few questions about it :
1) For the moment, the `IDE` class only handles the `master` device. Do you
think that it could be interesting to handle the `slave` device too?
If so, how could we give the information to the `IDE` class?
2) I don't have implemented the `write` function yet, how should I do that?
I saw that in the `VirtioBlk` class it's the same thing, what about it? And shouldn't
we have an Interface `IBlkDriver` which would be implemented by `IDE`, `VirtioBlk`
and the other block devices?
3) Could you explain me a little how should the FileSystem work in IncludeOS?
What if I want to bind the IDE with a FS? Shouldn't we make the `hw::Disk`
class implement the `IDiskDevice` interface?
Cheers.
=> First draft of IDE device driver implementation

api/net/tcp.hpp, examples/demo_service/service.cpp, examples/tcp/Makefile, examples/tcp/debug/service.gdb, examples/tcp/run.sh, examples/tcp/server.py, examples/tcp/service.cpp, src/net/tcp.cpp, src/net/tcp_connection.cpp, src/net/tcp_connection_states.cpp
**TCP example:**
Made a small example with help of a python "server" which demonstrates reading and writing to a incoming and outgoing connection.
I'm using `netcat` to connect to my IncludeOS VM (port 80). Every message sent to IncludeOS will be sent to python server (port 1337 host), returned back to IncludeOS, and again returned back to the client.
=> examples: cleaned up demo_service and added a new tcp example

api/net/tcp.hpp, src/net/tcp.cpp, src/net/tcp_connection.cpp, src/net/tcp_connection_states.cpp, test/tcp/service.cpp
TCP can now parse and add options.
`test/tcp` passed locally.
Solves #417.
=> tcp: Added header options support

api/kernel/vga.hpp, src/boot/bootloader.asm, src/kernel/vga.cpp, test/vga/vga.cpp
Instead of using BIOS-interrupts the bootloader just writes to VGA memory. A boot screen is added, which is nice for letting people know something happened, in i.e. virtualbox.
=> Added boot screen, removed BIOS-interrupts

api/net/tcp.hpp, etc/install_osx.sh, examples/demo_service/Makefile, examples/demo_service/service.cpp, examples/tcp/Makefile, examples/tcp/service.cpp, src/debug/test_tcp.cpp, src/net/tcp_connection_states.cpp, test/tcp/service.cpp, test/tcp/vbox.sh, test/timers/Makefile
**TCP:**
Changed `onDisconnect` to return a `struct Disconnect` instead of a string.
Adapted this change to services (test, demo).
**Examples:**
Less output spam. Also now using the new Makefile.
**OSX build script:**
#435
I'm not sure forcing the user to install Xcode command line tools is the right choice. Added a warning that installation MAY not complete.
Opinions?
=> tcp: small changes to api, adapted test & examples + changes to os x script

api/fs/disk.hpp, api/kernel/terminal.hpp, api/memdisk, src/Makefile, src/debug/test_disk.cpp, src/fs/disk.cpp, src/kernel/terminal.cpp, test/fat/fat16.cpp, test/fat/fat32.cpp
To use any disk with terminal I had to remove template from disk. Everything should work as expected, although we have temporarily lost the ability to select filesystem. On the bright side, we now have filesystem commands in the terminal given a prepared disk, and we no longer need to know about FAT32 when creating disks.
=> fs: Remove template, term: Add filesystem commands

api/hw/nic.hpp, api/kernel/os.hpp, api/net/inet_common.hpp, api/net/packet.hpp, api/virtio/virtio.hpp, api/virtio/virtionet.hpp, src/net/ethernet.cpp, src/net/packet.cpp, src/virtio/virtio_queue.cpp, src/virtio/virtionet.cpp, test/transmit/Makefile, test/transmit/README.md, test/transmit/run.sh, test/transmit/service.cpp
* `VirtioNet::transmit` will now check if the incoming packet is chained, and if so transmit the whole chain
* If the virtio transmit-ring is full, the remaining packet chain will be saved and new packets will be added to that chain
* When the virtio device notifies the driver that packets have been sent:
* A) We transmit any waiting packets using `transmit` (and if there's not enough space in the ring, we requeue the remaining packets)
* B) If the transmit buffer is empty (no waiting packets), we call the new `buffer_available_event`
Next up is to make the buffer available event visible in inet
=> VirtioNet now buffers outgoing packets

api/net/inet4.hpp, api/net/inet4.inc, api/net/inet_common.hpp, api/net/ip4/udp.hpp, src/debug/test_service.cpp, src/net/ip4/udp.cpp, test/UDP/service.cpp
Adds the free buffers distribution algorithm, which is very simple by design right now. At first we give each registered protocol a fair share of the total pie, then in the second phase we try to hand out as much as possible to each protocol. A better version will keep all phases equally fair.
Also finished the sendq implementation in UDP.
=> net: Distribute free buffers, udp: Remove gather phase

src/debug/test_service.cpp, src/net/ip4/udp.cpp, src/net/ip4/udp_socket.cpp
UDP swallowed buffers too fast due to immediate-flushing behavior. Now fixed
=> udp: Fix buffer release issue

api/hw/pit.hpp, api/net/tcp.hpp, test/timers/service.cpp
.. and PIT now supports seconds as `double`.
=> tcp/pit: fixed ambiguous member call on write

api/fs/disk.hpp, api/hw/pit.hpp, api/net/dhcp/dh4client.hpp, api/net/inet.hpp, api/net/inet4.hpp, api/net/inet4.inc, src/debug/test_service.cpp, src/fs/disk.cpp, src/kernel/terminal_disk.cpp, src/net/dhcp/dh4client.cpp, test/fat/fat16.cpp
.. and dhcp timeout, on_config for inet and option for disabling dhcp output
=> fs: Add support for instantiating custom filesystem

api/net/tcp.hpp, src/net/tcp.cpp, src/net/tcp_connection.cpp, src/net/tcp_connection_states.cpp, test/tcp/service.cpp, test/vmrunner.py
* TCP `WriteQueue`: No longer queues Packets for retransmission, but creates new ones on demand by not releasing WriteBuffers until fully acknowledged.
* `vmrunner.py` now works without kvm.
=> tcp: new write queue implementation + fix to vmrunner.py

api/net/tcp.hpp, src/net/tcp_connection.cpp, src/util/async.cpp
Changed to rather "renew" (allocating a new) buffer instead of reseting the current one. Cost between `clear` (memset) and `renew` (make_shared) maybe is the same? It also makes Connection release the ownership of the buffer when giving it to the user via user callback.
=> tcp: now renewing instead of reseting read buffer

README.md
Only build from bundle is done at the moment. These shields are based on the pipeline functionality in Jenkins and they will automatically perform all tests approved by the validate_test.py script in the test folder.
=> Added back shields

api/sys/features.h, api/sys/math.h, api/sys/time.h, api/sys/wchar.h, etc/build_llvm32.sh, etc/newlib_clang.patch, install.sh, src/Makefile, src/seed/Makefile
Updated newlib to latest version
=> Newlib / binutils update

test/bufstore/run.sh, test/bufstore/test.py, test/bufstore/test.sh, test/bufstore/vm.json, test/crt/test.py, test/crt/vm.json, test/quick_exit/README.md, test/quick_exit/test.py, test/quick_exit/vm.json, test/tcp/test.py, test/term/term.cpp, test/timers/README.md, test/timers/test.py, test/timers/vm.json
Timers, quick_exit, crt and bufstore are now implemented with python.
I also removed the run.sh and test.sh from the bufstore directory. Not sure if you want to keep these or not though.
=> Four new tests implemented

api/kernel/irq_manager.hpp, src/hw/apic.cpp, src/hw/ide.cpp, src/hw/pit.cpp, src/hw/ps2.cpp, src/hw/serial.cpp, src/kernel/irq_manager.cpp, src/kernel/os.cpp, src/virtio/block.cpp, src/virtio/virtio.cpp, src/virtio/virtionet.cpp
Might solve #545. @fwsGonzo you'll probably have opinions on how I name this one. As you can see I've added a numeric argument in case we'd want to use the getter for several instances. I'm not sure we want to expose a getter for each CPU though - I think it would probably be better to have a static function, or some other global IRQ supervisor that could assign your IRQ to whichever CPU was in charge of that particular line (I know they use IRQ balancing in Linux by default) 
However, we don't need to pollute the global namespace, plus avoiding using global constructor for the `bsp_idt`-instance seems to solve #545 for me on trident3.
=> Wrapped the IRQ_handler instance (bsp_idt) in static singleton. 

api/net/ip4/packet_ip4.hpp, api/net/tcp.hpp, examples/demo_service/service.cpp, src/net/ip4/ip4.cpp, src/net/tcp.cpp, src/net/tcp_connection.cpp, src/net/tcp_connection_states.cpp
* Made size/length calculation more dynamic
* TCP Packet is now using functions inside PacketIP4 to determine offsets.
* Added prefix to a lot of functions.
Hopefully solves #565 (earlier failed scenario is now working).
Also made demo only reply with HTML on `GET / ` requests.
=> Refactored PacketIP4 and TCP::Packet

api/net/tcp.hpp, src/net/tcp.cpp, src/net/tcp_connection.cpp
Last step is `TCP` cleaning up a Connection (closing). It removes the `Connection_ptr` from it's map, so the last pointer goes out of scope, destroying the Connection and releasing all it's resources.
Due to Connection_ptr being copied into lambdas, the Connection always had one (or more, depending on how many callbacks copying ptrs) instance of itself, making it invincible (the bad kind).
```
conn->read(1024, [conn] ... // copies here
```
Connection now calls `reset()` on all `delegate` (callbacks) right before closing.
=> tcp: Clean up (possible) copies of shared_ptr in callbacks

etc/install_from_bundle.sh, etc/install_osx.sh, etc/install_ubuntu.sh, install.sh
One common ./install.sh script for both mac os x and ubuntu. Moved all common functionality to the ./etc/install_from_bundle.sh and moved all ubuntu specifics to ./etc/install_ubuntu.sh.
If accepted the wiki for installation on osx will need to be updated to reflect this change. (calling ./etc/install_osx.sh still works though)
=> New install scripts

test/stress/test.py, test/vmrunner.py
Added a simple wait function to the stress/test.py which makes sure it does not continue until the TIME_WAIT connections are below a set limit. Not sure if this is a solution you want, but it makes sure this test does not interfere with other tests.
Last commit fixes some irregular function calls.
=> Possible fix to stress + tcp test failing

etc/get_latest_binary_bundle_asset.py, etc/install_from_bundle.sh
Does not rely on tags at all any more. Will now rather find the latest release from the json output from [releases](https://api.github.com/repos/hioa-cs/IncludeOS/releases). Small change to the python script which now let's you extract multiple fields from the json output. Fix for #615
=> A fix for pulling down tags

test/vmrunner.py
Changes to the sudo call in ubuntu 16.04 made the old way of calling the qemu process with sudo not work.
Now displays error if vmrunner.py is not called with sudo.
=> Removed sudo calls from vmrunner script

etc/qemu_cmd.sh
Looks like I broke it for everyone running qemu nested by setting host as default. Fix that now.
=> etc: cpu host should not be default

test/GSL/test.py, test/STL/test.py, test/UDP/test.py, test/bufstore/test.py, test/crt/test.py, test/exceptions/test.py, test/fat16/test.py, test/fat32/test.py, test/stress/test.py, test/tcp/debug.py, test/tcp/test.py, test/timers/test.py, test/transmit/test.py, test/virtio_block/test.py, test/vmrunner.py
Introduced `vm.make()`. Was earlier called indirect, is now required to be called before `boot()`.
Can be chained as so: `vm.make().boot()`.
Reason is to support custom make: `vm.make(["FILES=horse.cpp", "DISK=nsa.log"]).boot()`
=> Added make step to vmrunner

README.md
Removes ubuntuism and adds missing commands in command line examples, adds link to Contribution Guidelines in the wiki.
=> documentation: updated README

api/net/ethernet.hpp, src/net/ethernet.cpp, test/ethernet/Makefile, test/ethernet/README.md, test/ethernet/ethernet_module_test.hpp, test/ethernet/run.sh, test/ethernet/service.cpp, test/ethernet/test.py, test/ethernet/test.sh, test/ethernet/vbox.sh, test/ethernet/vm.json, test/ipv4/ipv4_module_test.hpp
* Fix Ethernet MAC address string representation to print leading zeros
* Added test folder for net::Ethernet module
=> ethernet.hpp: Fix Ethernet MAC address string representation to print leading zeros 

api/async, api/hw/apic.hpp, api/hw/apic_timer.hpp, api/kernel/rdrand.hpp, api/kernel/timer.hpp, api/timer, src/Makefile, src/debug/test_service.cpp, src/hw/apic.cpp, src/hw/apic_timer.cpp, src/kernel/os.cpp, src/kernel/timer.cpp
Oneshot and periodic timer system that reschedules itself until all timers are handled.
The timer system does not start until the underlying hardware system signals ready. This means that timers will work during service start, even if the hardware calibration process is not yet done. This is the case for the APIC timer, which is calibrated from a 10ms PIT timer.
Long periods would ordinarily overflow the APIC timers tick register, but its saturated, and the timer system corrects itself by starting a new hardware timer if no timers' timestamp were overshot.
The system relies on a correct cpu MHz implementation. The system readjusts every time a timer ticks, which happens at the longest every 2 minutes, so drift is not a problem.
=> Timer system, APIC timer

api/net/ip4/addr.hpp, api/net/ip4/ip4.hpp, api/net/tcp/common.hpp, api/net/tcp/connection.hpp, api/net/tcp/headers.hpp
`struct IP4::addr` is now `net::ip4::Addr`, moved inside `net/ip4/addr.hpp`. This is to reduce dependencies.
Also small helper `tcp::buffer_t net::tcp::new_shared_buffer(uint64_t length)` added to `net/tcp/common.hpp`
=> Made IP4::addr independent - moved to ip4 namespace

src/kernel/elf.cpp, src/kernel/timer.cpp, test/kernel/integration/timers/timers.cpp
```
Conns/sec 5431.600000  Local clients 0  Timers: 1
*** Listing 12 results (104128 samples) ***
34.84%     36282: VirtioNet::handle_deferred_devices()
5.39%      5616: VirtioNet::msix_xmit_handler()
3.68%      3832: VirtioNet::msix_recv_handler()
3.08%      3211: VirtioNet::recv_packet(unsigned char*, unsigned short)
2.78%      2892: OS::default_rsprint(char const*, unsigned int)
2.74%      2857: Timers::oneshot(std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000ll> >, delegate<void (unsigned int)> const&)
2.25%      2342: 0xc3f000ff
2.12%      2208: net::TCP::bottom(std::__1::shared_ptr<net::Packet>)
1.38%      1442: net::TCP::transmit(std::__1::shared_ptr<net::tcp::Packet>)
1.07%      1119: void delegate<void (std::__1::shared_ptr<net::Packet>)>::method_stub<net::Arp, …
```
=> Huge optimization for timers, solve ELF-related issue with symbol type

test/util/unit/membitmap.cpp
Increases test coverage for membitmap.hpp from 96.4% to 98.2%
=> test: verify no clear bits can be found when all bits are set

api/utility/fixedvec.hpp, src/kernel/profile.cpp
Fixed vector needs its own header in order to be testable
=> profile: Move fixedvec into its own header file

api/kernel/rtc.hpp, src/net/tcp/connection.cpp
=> TCP now forces close when retransmission limit is reached

src/seed/Makefile, src/seed/Makelib
In src/Makefile clang++ is already allowed as compiler, but not in seed projects.
This change would be nice for arch linux users.
=> clang++ as compiler binary name is supported for seed projects

test/test.py
test.py feels like a bit of a mess. Integrating the test categories into the test class will probably be a better option. Also integrating both the validate_test and validate_all script into at least the same script will be a good move. As of right now this is hard to maintain. 
This makes changes to how jenkins calls tests, but will require less manual interaction with Jenkins in the future.
=> Changes to filtering of test categories

install.sh
Linux Mint binary and packet-compatible with Ubuntu, so it can be simple handled as Ubuntu.
=> Add Linux Mint to supported distros

api/kernel/cpuid.hpp, src/kernel/cpuid.cpp
Also moves struct cpuid_t from cpuid.hpp to cpuid.cpp as it's only used internally
--
@fwsGonzo also mentioned:
> honestly, we wanted to redo the whole cpuid thing for a while now
> its less than a days work to do it right, and there are a few other parts of our code that will need it, such as kvm paravirtual stuff
> but no one is working on it right now
If I could get some input on how you want it done (does it need to support _all_ cpu features?) and other requirements (can a hypervisor change cpuid during runtime / after boot, or can one assume that the result of a cpuid call is always the same?), then I could probably get it done.
I got a few ideas of how to implement it. Export an enum class with all features `enum class Feature { SSE3, FPU, ... };` and a single static function `bool …
=> Fixes incorrect cpuid call

src/drivers/virtioblk.cpp
Simply initialise VirtioBlk::inflight to 0 in the constructor, to allow reference count to reach 0 (and fire the callback).
=> Fix bug to allow reading large (>4kish) files.

README.md, etc/create_bridge.sh, etc/install_build_requirements.sh, install.sh
So this is basically just some additional return / exit value checks in the install scripts to make it more robust. I found most of these problems when trying to install IncludeOS under Debian stable. Most of the build steps failed but the script kept going, and finally outputted "Done! Test your installation with ./test.sh", which was kind of .. not so good. This commit partially solves #620 .
I removed the "sudo" part from the README since the script will use sudo when needed. Using sudo when executing install.sh will also build and install everything as root:root and that is probably not want most users want.
I'm not sure if the check for "sudo" is necessary since all supported systems have sudo installer per default (?). Debian does however not, and that's why I added it.
=> Adds missing exit value checks in install script

api/kernel/cpuid.hpp, src/kernel/cpuid.cpp
First draft of cpuid rewrite. Open questions:
- Is the cache necessary? I did some research and found that cpuid is a pretty expensive call, but maybe the overhead of the cache makes it useless.
- Maybe add vendor information to each `FeatureInfo` since not all features are applicable to both Intel and AMD CPUs. At the moment the user needs to first check `isIntelCpu` or `isAmdCpu` before asking for a specific feature (if the feature is not applicable to both).
=> kernel: draft of cpuid rewrite

etc/install_osx.sh, src/seed/Makefile, vmbuild/elf.h, vmbuild/elf_binary.hpp, vmbuild/vmbuild.cpp
* Fixed vmbuild compile errors as explained in #874.
* Updated binutils (2.25 => 2.27) for `objcopy --update-section`
* Also installs `strip` on macOS, now set with `STRIP_INC`
Solves #874 (would be nice if someone else could confirm this)
=> Fixed building on macOS (master)

etc/create_bridge.sh, etc/install_build_requirements.sh, install.sh
* Adds check of installed packages before calling sudo apt-get
(Ubuntu only)
* Adds check of created / configured bridge before calling
sudo brctl and sudo ifconfig
You can now run ./install.sh without needing to enter password for sudo if everything is already installed.
**NOTE:** Can someone test this on other platforms? I'm not 100% sure if OS X, Fedora and Arch has the command `ip`. Otherwise we need to add a check for that and always configure the bridge, even if it's not actually needed.
=> install: do not use sudo if not needed

api/profile, examples/scoped_profiler/Makefile, examples/scoped_profiler/README.md, examples/scoped_profiler/run.sh, examples/scoped_profiler/service.cpp, src/kernel/profile.cpp
Notes:
* Calls cpuid before rdtsc due to http://stackoverflow.com/a/2918125/969365 (not sure if it's actually needed though)
* Not sure if we really need to add an example service. If you don't want it I can remove it.
I also did some testing before and after the "ptrstuff" commits (on bd60272f4d12c5530ef175ea472de8eca07f97fc and on adcf38c3f3df5cddd4e7592a719950df5d5fa70d):
Before:
```
--------------------------------------------------------------------------------
29.366431 |    6013 | VirtioNet::msix_recv_handler()
15.438494 |    3003 | VirtioNet::msix_xmit_handler()
--------------------------------------------------------------------------------
```
After:
```
Average Time (us) | Samples | Function Name
-------------------------------------------------------------------------------- …
```
=> profile: Adds ScopedProfiler

CMakeLists.txt, examples/256_color_vga/CMakeLists.txt, examples/CMakeLists.txt, examples/STREAM/CMakeLists.txt, examples/demo_service/CMakeLists.txt, examples/dualnic/CMakeLists.txt, examples/smp/CMakeLists.txt, examples/snake/CMakeLists.txt, examples/tcp/CMakeLists.txt, src/CMakeLists.txt, src/boot/CMakeLists.txt, src/drivers/CMakeLists.txt, src/linker.ld, vmbuild/CMakeLists.txt, vmbuild/elf.h, vmbuild/vmbuild.cpp
This is a rough first prototype that allows building of unikernels
within examples/ with cmake. Lots of room for improvements. Also
an installed ~/IncludeOS_Installation is expected.
To build (on Linux), goto to the unikernel src directory, and do:
~~~
$ mkdir build
$ cd build
$ CXX=/usr/bin/clang++ CC=/usr/bin/clang cmake ./..
$ make
~~~
To switch configuration switches, use ccmake within the build directory.
=> [build] Build libos.a as and unikernels within /example with cmake

etc/install_osx.sh
Long story short, osx needs objcopy to build even the examples at a basic level. This small change in the install_osx.sh file lets people know, up front, how to build the basic example projects.
=> Osx missing objcopy

src/memdisk/memdisk.py
Archlinux by default users python 3+ this causes issues with the memdisk.py script i have modified the script slightly so that it is compatable with python 2.x and 3.x to hopefully resolve some make errors with less pain i have tested the change on an Archlinux and Centos server with positive results.
Before:
```
python -V ->
Python 3.5.2
python src/memdisk/memdisk.py ->
print "Renaming " + osx_dmg + " => " + image
^
SyntaxError: Missing parentheses in call to 'print'
```
```
python2.7 -V ->
Python 2.7.12
python2.7 src/memdisk/memdisk.py ->
```
After:
```
python src/memdisk/memdisk.py ->
```
Happy to answer any questions if needed :)
Thanks for the great work guys im just staring out in unikernels hope i have more pulls to come :D
=> Making memdisk.py python3 and python2 compatable

src/Makefile, src/kernel/cpuid.cpp
- scoped enumerations cannot be shortened using 'using'.
- test 'clang' C compiler in CC detection in the Makefile.
(cherry picked from commit 1654ffbc3bc6df4c456438c670c2b968539f0d55)
=> fix build with clang-3.9

etc/install_build_requirements.sh
This patch addresses issue #929
=> install_build_requirements.sh:Add missing label to support LinuxMint

CMakeLists.txt, cmake/cross_compiled_libraries.txt, etc/Makefile.seed.in, examples/CMakeLists.txt, src/CMakeLists.txt, src/boot/CMakeLists.txt, vmbuild/CMakeLists.txt, vmbuild/vmbuild.cpp
I'm trying to make icrd compile as external project. So far it works except libvirtnet.a support (as now this is a libarry, not an object file).
How to: from within checkout-out includeos project:
~~~ bash
$ mkdir build
$ cd build
$ CMAKE_INSTALL_PREFIX=~/tmp CXX=/usr/bin/clang++ CC=/usr/bin/clang cmake ./..
$ make
$ make install
~~~
Now everything will be installed into ~/tmp , including a custom Makeseed
Then checkout ircd and change its Makefile  (mostly adapt path to Makeseed file):
~~~
iff --git a/Makefile b/Makefile
index fe9eb34..27f77c7 100644
--- a/Makefile
+++ b/Makefile
@@ -14,18 +14,18 @@ FILES = service.cpp ircd.cpp client.cpp client_new.cpp client_msg.cpp client_cmd
DISK=
-DRIVERS=virtionet
+DRIVERS=
LOCAL_INCLUDES=
ifndef INCLUDEOS_INSTALL …
=> WIP: Work on external builds (3rd party unikernels)

vmbuild/elf_binary.cpp
This pull request fixes problem found out by myself and described in issue #942.
Solutions resolves the problem by casting Section_header's sh_size to index_type (aka std::ptrdiff_t) parameter of Elf_binary::Span.
=> Fix issue #942 regarding vmbuild not compiling

.gitignore, Dockerfile, etc/install_all_source.sh, seed/docker_run.sh
This allows the following workflow to run a new IncludeOS service:
```
$ cp -r seed/ <service_path>
$ cd <service_path> && ./docker_run.sh
```
The `./docker_run.sh` script passes arguments through to docker (if no arguments are passed, it will call `run.sh`):
- to build an image (without running): `./docker_run.sh make`
- to start a new bash session: `./docker_run.sh bash`
Two unresolved issues:
1. I couldn't figure out how to bind ports on a running service to the docker host. This means that if you want to `curl` / `ping` the service, you need to start a bash shell in the container and build / test inside the container. If someone knows how to get this working, I would be more than happy to improve this.
2. `./docker_run.sh` assumes that the image is tagged with `includeos`. This tag is …
=> Add docker based image builder / runner

etc/install_from_bundle.sh, test/kernel/integration/block/service.cpp, test/kernel/integration/block/vm.json, test/kernel/integration/block/vm1.json, test/net/integration/dhcp/vm.json, test/skipped_tests.json, test/test.py
- Enabled the block test as it can now run alone.
- test.py no longer has a unit test category as that is handled by cmake.
- install_from_bundle.sh now runs make clean before make.
=> Tests: Readded block test, make clean in install_from_bundle

etc/scripts/qemu_cmd.sh, etc/service.cmake, seed/CMakeLists.txt, seed/cmake_build.sh, seed/run.sh, test/fs/integration/fat16/CMakeLists.txt, test/fs/integration/fat32/CMakeLists.txt, test/fs/integration/memdisk/CMakeLists.txt, test/fs/integration/virtio_block/CMakeLists.txt, test/kernel/integration/kprint/CMakeLists.txt, test/net/integration/dhcp/CMakeLists.txt
I'm doing this to avoid confusion with the old $INCLUDEOS_INSTALL, which meant the contents of the folder where all of IncludeOS is installed. $INCLUDEOS_PREFIX is intended to reflect the $CMAKE_INSTALL_PREFIX supplied when installing IncludeOS with cmake, which defaults to `/usr/local`
=> Cmake: Change INCLUDEOS_INSTALL to INCLUDEOS_PREFIX

api/platforms/unik.hpp
due to conflicts with another application, we've changed the udp broadcast port in UniK instance listener
=> fix udp listen port to 9967

api/kernel/os.hpp, api/profile, src/kernel/kernel_start.cpp, src/kernel/os.cpp, src/kernel/profile.cpp, src/net/tcp/tcp.cpp
Also move the initial call to OS::event_loop from OS::start to kernel_start to allow running scoped profilers in OS::start
=> Add optional profilers to OS start, fix issue where ScopedProfiler constructor could be moved around

test/CMakeLists.txt, test/util/unit/uri_test.cpp
Lest tests can contain [tags] in their description. Lest skips tests that begin with `[.`, so we can tag expected failures to make Lest skip the few failing tests instead of commenting out a full test file in CMakeLists.txt
=> test: re-enable uri tests, skip expected failures

api/util/fixed_queue.hpp, test/CMakeLists.txt, test/util/unit/fixed_queue.cpp
First in, first out.
Static size wrapping. 
No copy, only overwrite preexisting elements.
type safe.
=> Added new container fixed_queue and corresponding unit tests

api/net/http/client.hpp, api/net/http/common.hpp, api/net/http/connection.hpp, api/net/http/error.hpp, api/net/http/header.hpp, api/net/http/request.hpp, api/net/http/response.hpp, api/net/tcp/connection.inc, api/net/tcp/tcp.hpp, src/CMakeLists.txt, src/net/http/client.cpp, src/net/http/connection.cpp, src/net/http/header.cpp, src/net/http/message.cpp, src/net/http/request.cpp, src/net/http/response.cpp, src/net/tcp/connection.cpp, src/net/tcp/connection_states.cpp, src/net/tcp/tcp.cpp, test/misc/binary_check/test.sh, test/net/integration/http/CMakeLists.txt, test/net/integration/http/README.md, test/net/integration/http/run.sh, test/net/integration/http/service.cpp, test/net/integration/http/test.py, test/net/integration/http/vm.json
* Simple randomization of ports (got really tired of all resets because of the same outgoing port being used when service got restarted a lot)
* Some minor changes to TCP, makes it possible to correctly write (queue) and hook up on read before connection has been established.
* HTTP Client (WIP)
* Update GSL to latest version
=> HTTP Client, TCP improvements and update GSL

test/plugin/integration/unik/test.py, test/util/integration/tar/test.py, test/util/integration/tar_gz/test.py
The way the import is done is still not the proper way to do it. This is still not a python module, for that it will require a setup.py as well. I'll see to this later.
=> Fixed wrong vmrunner imports

src/include/kprint
> Before a function that has initialized a va_list object with va_start returns, the va_end macro shall be invoked.
[va_list](http://www.cplusplus.com/reference/cstdarg/va_list/)
If this is true, we should probably do it. If this is *not* true in IncludeOS, we should probably add a comment.
=> kprint: add va_end

etc/install_build_requirements.sh, etc/scripts/create_bridge.sh
1. Only install the "needed" packages (e.g. the ones that are not currently installed) on Arch Linux
2. brctl show differs in output on Arch Linux when the bridge does not exist
=> Better support for Arch Linux

test/CMakeLists.txt, test/kernel/unit/memmap_test.cpp, test/util/unit/logger_test.cpp, test/util/unit/statman.cpp
For some reason, logger_test was not present in the unit test CMakeList. Added it and fixed warnings. Also re-enabled statman & memmap unit tests.
=> test: updated logger_test

lib/mana/src/middleware/butler.cpp, lib/mana/src/middleware/director.cpp, lib/mana/src/server.cpp
Due to `URI::to_string` now returning `string_view` (and to avoid `to_string().to_string()`) it now makes use of the overloaded `std::string` operator. 
Maybe some of the code in mana should be refactored to operate with URI's instead of strings.
=> mana: Use URI string operator due to changes of to_string

api/posix/arpa/inet.h, test/CMakeLists.txt
There *has* to be a better way (suggestions very welcome!), but this makes it possible to build/run unittests on macOS again with native compiler, no symlinking tricks necessary.
=> test: make unittests buildable on macOS

api/net/http/client.hpp, api/net/http/connection.hpp, api/util/uri.hpp, src/net/http/client.cpp, src/net/http/connection.cpp, src/util/uri.cpp
It caused some weird stuff in the HTTP client where values where lost when URI got moved, making the Request invalid with corrupt path and empty `Host: `.
=> Updated URI move and copy

api/net/dns/client.hpp, api/net/dns/dns.hpp, api/net/http/common.hpp, api/net/inet_common.hpp, api/net/ip4/udp.hpp, api/net/ip4/udp_socket.hpp, api/net/super_stack.hpp, lib/mana/include/mana/server.hpp, src/net/dns/client.cpp, src/net/dns/dns.cpp, src/net/http/client.cpp, src/net/http/connection.cpp, src/net/ip4/udp.cpp, src/net/super_stack.cpp, src/net/tcp/tcp.cpp
For some reason the the callback delegate the HTTP Client sometimes ended up as nullptr. Maybe due to new delegate implementation. Seems to be fixed by using `spec::dynamic`. If anyone can explain why, please do :D
TCP and UDP are now using dynamic (ephemeral) ports in the range described by IANA in [RFC 6335](https://tools.ietf.org/html/rfc6335). In other words, the outgoing ports are now in range of `49152 - 65534`.
Improved the DNS Client by adding timeout on resolve requests (5s default). It now also reuses one UDP socket. Also added transaction ID matching on incoming responses.
Also a fix for #1073 sneaked in before I noticed #1074 - please merge that one first (when sorted).
=> HTTP Client improvements, DNS Client rework, RFC 6335

vmrunner/vmrunner.py
The idea with defaulting to virtionet is that qemu will add a default (Intel) network device anyway, unless you explicitly ask it not to. Since most of our services have a single network interface it seems nice not having to specify vm.json for those. 
Mac addresses should always have been optional - they were never required by the schema but implicitly in the code.
=> vmrunner: make mac optional, use virtio/tap by default

etc/install_osx.sh
I haven't really been able to test this since my environment is very hacky and I got python installed with brew.
=> install: Added pip installation & modules to macOS install #1087

api/posix/sys/mman.h, api/sys/dlfcn.h, api/sys/signal.h, src/CMakeLists.txt, src/crt/c_abi.c, src/hw/pci_device.cpp, src/kernel/elf.cpp, src/posix/dlfcn.cpp, src/posix/sys/mman.cpp, vmbuild/elf_syms.cpp
... to make porting TCC possible
Also, fix for rebuild-into-crash problem on macOS
=> Important PCI fix, various posix and linux stubs

api/net/http/client.hpp, api/net/http/client_connection.hpp, api/net/http/connection.hpp, diskimagebuild/CMakeLists.txt, diskimagebuild/fat_internal.hpp, diskimagebuild/writer.cpp, src/CMakeLists.txt, src/net/http/client.cpp, src/net/http/client_connection.cpp, test/CMakeLists.txt, vmbuild/CMakeLists.txt, vmbuild/vmbuild.cpp
Some WIP on HTTP for lightweight server.
Due to the new `<sys/signal.h>` our tools including IncludeOS sys no longer builds on Mac. Did some changes to avoid including our sys when building tools.
=> Some HTTP Refactoring + fixes to build issues on Mac

api/net/http/header.hpp, api/net/http/message.hpp, api/net/http/response_writer.hpp, api/net/http/server.hpp, etc/library.cmake, src/net/http/header.cpp, src/net/http/response_writer.cpp, src/net/http/server.cpp, test/net/integration/http/service.cpp
Made the `Response_writer` API simpler to use. Currently only supports one write. It's possible to extract the underlying TCP Connection and do whatever you want to.
The changes can be seen in the http test.
=> Updates to HTTP Server

.gitignore, test/testrunner.py
In order to obtain proper shields with test coverage we needed a junit implementation within our testrunner.py script. To generate `output.xml` file used by jenkins (and shields.io) use the `-j` option. 
[Example](https://jenkins.includeos.org/view/All/job/shield_mnordsletten/)
This can enable:
- A clearer split between build status, and test status in the readme.
- All pull requests can report how many tests actually failed. 
Required some small rewrites of the testrunner.py. It simplifies the way tests are run, by adding both stress test and the misc tests to be discovered at an earlier stage.
=> Support for test-coverage shields

CMakeLists.txt, etc/service.cmake, vmbuild/CMakeLists.txt, vmbuild/elf_syms.cpp
This fixes issue #1040 for me. Ideally I guess we should also check that the binary doesn't contain any normal symbols. However, with the current build system you'll always get an empty `.elf_symbols` section from the linker script whenever a new binary is produced. If that's the case pruning will go ahead as before.
=> Avoid pruning/moving elf-symbols twice

api/kernel/syscalls.hpp, src/kernel/syscalls.cpp, test/net/unit/cookie_test.cpp, test/net/unit/http_response_test.cpp, test/util/unit/base64.cpp
Support for clockid_t/CLOCK_REALTIME differs between OS X/macOS versions. Now builds on both Mac OS X El Capitan and macOS Sierra.
=> test: unittest workarounds for OS X/macOS

etc/boot, etc/install_build_requirements.sh, etc/install_from_bundle.sh
* Use `env python2` instead of `env python` in the `boot` script
* Install required `python2 python2-jsonschema python2-psutil` packages
* Explicitly add `clang-3.9` support
=> Improve Arch Linux compatibility

src/util/uri.cpp
Calling `back` on a `string_view` where the condition `empty() == true` results in undefined behavior...
=> util: Fix bug in URI::host_is_ip4

src/crt/c_abi.c, src/drivers/heap_debugging.cpp, src/kernel/elf.cpp, src/kernel/kernel_start.cpp, vmbuild/elf_syms.cpp
This will prevent symbols & strings from being used in most if not all services.. the checksums have been verified to be preserved all the way into the ELF binary, but fails only inside kernel.
=> kernel: Verify symbols and strings with CRC32

src/net/ip4/icmpv4.cpp
#include <os> is extraneous here, we don’t need to take on the
dependency. The icmpv4.hpp is short a ../ in its relative pathing, but
regardless should use <net/ip4/icmpv4.hpp> directly instead. This
mirrors the styling in other ip cpp files.
=> icmpv4: Remove <os> include & fix broken include path

api/net/inet4.hpp
inet4.hpp no longer uses panic() from syscalls.hpp nor Dev:: from an
old version of devices.hpp. <hw/nic.hpp> is already included in the
shared file inet.hpp, so does not need to be included in inet4.hpp
specifically.
=> api/net/inet4.hpp - Remove extraneous #includes

api/net/tcp/rttm.hpp
std::max is used twice but is missing the corresponding include for <algorithm>.
=> tcp/rttm.hpp - Missing #include <algorithm> for std::max calls

api/net/inet.hpp
Was missing the = 0 for negotiate_dhcp pure virtual function, was causing missing symbol problems for me on compilation.
=> api/net/inet.hpp - Missing the = 0 for negotiate_dhcp pure virtual function

api/kernel/os.hpp, api/kernel/rtc.hpp, api/net/ip4/arp.hpp, src/kernel/os.cpp, src/kernel/rtc.cpp, src/net/dhcp/dh4client.cpp, src/net/inet4.cpp, src/net/ip4/arp.cpp, src/net/tcp/rttm.cpp, src/posix/sys/select.cpp, src/posix/udp_fd.cpp, test/lest_util/os_mock.cpp, test/net/integration/http/service.cpp, test/net/integration/http/test.py, test/net/integration/tcp/service.cpp, test/posix/integration/udp/service.cpp
(reopening to trigger new testing, my apologies for the repeated open/close of this PR)
This PR adds boot_timestamp() & time_since_boot() to RTC, enabling us to remove the dependency on #include <OS> from the network stack classes.
OS:: & the network stack classes have been updated to call the new RTC:: functions.
Additionally, two posix classes have been updated to directly #include <kernel/os.hpp>. Several already did, but these two were previously indirectly including it via the net classes.
=> RTC - Support boot_timestamp & time_since_boot

README.md
- Due to shields.io having some load issues the shield might not be visible at the moment. They are in the process of getting additional servers up.
- The junit generation part of testrunner.py has not been merged into master yet, so I can't generate the test coverage shield for it yet. I will add this as soon as it is merged.
=> Readme: Added integration test coverage to the readme

cmake/i686-elf-toolchain.cmake, etc/install_osx.sh, src/util/uri.cpp, test/lest_util/os_mock.cpp, test/util/unit/uri_test.cpp
Brew installed nasm should now be used on newer mac OS #1155.
URI was using wrong comparator when adding default ports - removed it all together and added tests that confirm it should be working #1161. (No longer case insensitive, but added cases for all UPPER).
Unittests now builds on Mac.
=> Solved Mac OS & URI issues

api/util/uri.hpp, src/util/uri.cpp
* Refactored `bind_port` function
* Fix bug in  `URI::host_and_port` method
* `URI::host_and_port` method now returns a `std::string` instead of a `std::experimental::string_view`
=> util: Minor changed to URI module

etc/boot
#837 and #1129 Broke the default mac installation as `python2` is not a valid command. This fixes that issue as it gives you a backup if `python2` does not exist.
=> Fix python version in boot for mac default installation

etc/install_build_requirements.sh, etc/install_from_bundle.sh, etc/scripts/create_bridge.sh, install.sh, test.sh
- Made parts of installation a lot quieter. Now only the cmake steps make noise. I'll look into suppressing output from this later.
- Fixed the function that guesses what compiler we have. It now works properly.
- When installing using terminal it now gives you a review of your install options and (y/n) prompt to continue.
- General reordering in install script and cleanup.
1. `sudo install.sh` and everything is installed in `/usr/local/includeos`
2. `install.sh` and you must set `INCLUDEOS_PREFIX`. If that is done everything is installed correctly. I created a prompt at the end urging the user to set `CC, CXX` and to add the `boot` utility to your `PATH`
=> Install: Start of new install script

api/util/delegate.hpp, test/util/unit/delegate.cpp
The fix is not pretty, however there is zero cost added, in some cases it's even more efficient.
The issue was that storing a lambda such as `[](auto arg) -> void { /* do stuff */  }` in an `aligned_storage_t` object has an all 0 memory layout, which is what is used to check if a delegate is empty: `reinterpret_cast<std::nullptr_t&>(storage_) == nullptr`
=> Fix empty generic lambda delegate issue

api/net/tcp/common.hpp, api/net/tcp/connection.hpp, api/net/tcp/listener.hpp, api/net/tcp/options.hpp, api/net/tcp/packet.hpp, api/net/tcp/tcp.hpp, examples/demo_service/service.cpp, src/net/tcp/connection.cpp, src/net/tcp/connection_states.cpp, src/net/tcp/listener.cpp, src/net/tcp/tcp.cpp, src/net/tcp/write_queue.cpp, test/net/integration/tcp/service.cpp, test/net/unit/tcp_write_queue.cpp, test/stress/service.cpp
**DACK**  (RFC 1122 p96):
More or less reduces outgoing packets with 50% when only receiving data. Tho not much of a performance gain since stopping and creating timers seems to cost just as much.
Default timeout set to `40ms` (maybe this is too low). Can be changed in application: `tcp().set_DACK(100ms);` A value of `0` will turn delayed ACK off.
**Window Scaling** (RFC 7323):
Receive and send window can now exceed 64KB, which means more data can be in flight. (Up to 1GB). Default is set to **256 KB** for trying it out. Gives a lot of performance when sending, not any when receiving (less depending on the window set..). 
**TCP Configure**:
The TCP instance that spawn new connections are now more configurable (still using default values set in `tcp/common.hpp`):
``` …
```
=> tcp: Delayed ACK, Window Scaling, Timestamps etc

api/util/delegate.hpp
Apparently casting a `std::aligned_storage_t` object to type `std::nullptr_t` with gcc like such: `reinterpret_cast<std::nullptr_t&>(storage_)` will always return `nullptr` even if the memory itself is not all zero.
Switching to size_t seems to work and not cost more.
=> Change empty delegate storage cast to size_t

api/kernel/irq_manager.hpp, api/net/link_layer.hpp, api/smp, src/arch/x86/apic_boot.asm, src/arch/x86/apic_revenant.cpp, src/arch/x86/apic_revenant.hpp, src/arch/x86/apic_timer.cpp, src/arch/x86/arch.cpp, src/arch/x86/gdt.cpp, src/arch/x86/smp.cpp, src/drivers/virtionet.cpp, src/drivers/virtionet.hpp, src/kernel/irq_manager.cpp, src/kernel/syscalls.cpp, src/kernel/timers.cpp, src/net/inet4.cpp, test/kernel/integration/smp/service.cpp
- Cache-aligned SMP per-cpu structures
- Experiment with cache-aligned IP-layer in virtionet
- Fix SMP bug that caused problems
- Automatically move network stacks to current CPU (if instantiated on that CPU)
=> Cache-aligned SMP per-cpu structures using std::array

etc/install_build_requirements.sh, install.sh
- Removed the checking we do for Ubuntu 14.04 as it is no longer supported by us
- All commonly named packages are now neatly listed
Also made cmake output default during installation, suppressible with `./install.sh -q`
=> Dependencies: Small cleanup of dependency install

api/net/http/client_connection.hpp, api/net/http/connection.hpp, api/net/http/server.hpp, api/net/http/server_connection.hpp, api/net/tcp/connection.hpp, api/net/tcp/options.hpp, api/util/async.hpp, lib/mana/src/response.cpp, src/net/http/client.cpp, src/net/http/client_connection.cpp, src/net/http/response_writer.cpp, src/net/http/server.cpp, src/net/http/server_connection.cpp, src/net/tcp/connection.cpp, src/util/async.cpp, test/net/integration/http/vm.json
A `Connection::Stream` can now be constructed with a `tcp::Connection_ptr`. This exposes only the most important functionality of a TCP Connection and is overridable (virtual). The idea is to have other "extension" of a TCP Connection inherit and override the Stream interface, and by that support secure connections.
I also made HTTP able to support HTTPS (TLS) connections by replacing Connection with Stream.
=> TCP Connection Stream interface

api/memdisk
Nobody reads comments! :) Adding the `deprecated` [attribute](http://en.cppreference.com/w/cpp/language/attributes) will make the compiler output an actual warning:
```
[ 55%] Building CXX object CMakeFiles/service.dir/test_stat_ftw.cpp.obj
/Users/ingve/IncludeOS/test/posix/integration/stat/test_stat_ftw.cpp:28:26: warning: 'new_shared_memdisk' is deprecated [-Wdeprecated-declarations]
static auto disk = fs::new_shared_memdisk();
^
/Users/ingve/IncludeOS_install/includeos/api/memdisk:37:34: note: 'new_shared_memdisk' has been explicitly marked deprecated here
[[deprecated]] inline Disk_ptr new_shared_memdisk()
^
1 warning generated.
```
=> fs: add deprecated attribute to new_shared_memdisk function

api/net/tls/server.hpp, src/CMakeLists.txt, src/drivers/virtionet.cpp, src/drivers/virtionet.hpp, src/virtio/virtio.cpp
The problem isn't in virtio anyways, and this allows for building virtio.cpp without the no-avx work-around
=> Work-around for ghost in the machine, remove another work-around

api/hw/block_device.hpp
=> hw: Add API documentation to the block device interface

etc/install_build_requirements.sh, install.sh
1. Much more visual what packages are installed by install.sh. (and yes there are colors)
2. Added another set of dependencies that are needed when installing with `INCLUDEOS_ENABLE_TEST`. These are automatically added when set to `ON`
3. Added command line options to `etc/install_build_requirements.sh`
```
/install_build_requirements.sh -h
Options:
-s System: What system to install on
-r Release: What release of said system
-c Only check: Will only check what packages are needed (will always print status as well)
-p Print install status: Flag for wheter or not to print dependency status
-d Dependencies to install: [build | test | all] are the options
```
```bash
ubuntu@test:~/IncludeOS$ ./install.sh
>>> Dependencies required:
Status          Package              Version
------ …
```
=> Improvements to dependency installation

test/CMakeLists.txt
Defer to existing definition in `api/smp` to avoid getting a bazillion warnings when building unittests
=> test: remove redundant definition of INCLUDEOS_SINGLE_THREADED

api/smp, api/util/sha1.hpp, cmake/post.service.cmake, src/CMakeLists.txt, src/arch/x86/acpi.cpp, src/arch/x86/smp.cpp, src/arch/x86_64/apic_asm.asm, src/kernel/os.cpp, src/kernel/syscalls.cpp, src/util/sha1.cpp
- Move INCLUDEOS_SINGLE_THREADED to cmake build system
- Don't read fs/gs in single threaded mode at all
- Fix SHA1 not using vectors for raw variant
and others
=> Some single-threaded work, SHA1 raw variant use vector

CMakeLists.txt, etc/build_chainloader.sh, install.sh, src/CMakeLists.txt, src/platform/x86_pc/CMakeLists.txt
This fixes building on mac for me. Still need a small fix to mac install script to trigger full build of dual toolchain though.
=> cmake: arch-specific objcpy target

.gitignore, CMakeLists.txt
This fixes the issue with ARCH environment variable breaking build folders
=> build: Cache ARCH, ignore build folders

api/net/dhcp/dh4client.hpp, api/net/inet.hpp, api/net/inet4.hpp, src/net/dhcp/dh4client.cpp, src/net/inet4.cpp
You can now ask Inet if its configured, or setup one or more on_config events. These will only be called when the stack is being configured (no timeout). Negotiating DHCP works as usual (with the timeout callback). DHCP no longer got a vector of config handler but one on_config (default is printing to console that it has timed out).
Opinions?
=> Changes to Inet on_config

README.md, etc/install_clang_version.sh, etc/install_dependencies_linux.sh
- all shields now use shields.io
- pip deps properly display
- clang install improvements
- g++-multilib is always needed, now a default dependency
=> clang_install: easier to install different clang versions

etc/install_dependencies_linux.sh, test/posix/integration/syslog_plugin/service.cpp, test/posix/integration/syslog_plugin/test.py
Should now pass the syslog_plugin test. This is a bit of a dirty hack while we await a better solution to cases like this. 
Only test that should not pass now is the posix/main test
=> syslog_test: Added seperate interface for test

src/arch/i686/arch_start.asm, src/linker.ld, src/platform/x86_pc/gdt.cpp, src/platform/x86_pc/gdt.hpp, src/platform/x86_pc/platform.cpp, src/platform/x86_pc/start.asm
Bottom line: 
- TLS support on i386
- Fixes SERIOUS issue on 32-bit with uninitialized stack guard
- 64-bit also lacked stack guard initialization, but was fixed in previous commit
=> i686: Add stack sentinel support, fix GDT issue, TLS verified

etc/install_dependencies_linux.sh
The g++-multilib package is not in the fedora repositories. 
This causes the installation to crash when it tries to install the dependencies.
=> Removed g++-multilib from fedora dependencies

src/kernel/syscalls.cpp, vmrunner/vmrunner.py
Added a new panic signature to emitted if and only if a panic happened. The reasoning is that we'd like to identify panic from `boot`, with extremely little chance of false positives. We also want:
* To be able to extract panic reports from log files
* Keep output nice and readable (hence non-printing ascii)
* To be able to look for panic cheaply while searching logs / output, but return early if no panic (first char is rare)
* Retain semantics of non printable acii chars. 0x15 is NAK (negative ack - error), 0x07 is Bell. (Yes, this might get picked up by your terminal, resulting in a visual / audible response if you're looking at boot output while panicking.)
* Have the panic signature be easily expressed in multiple languages, e.g. python, go, c++, javascript. `"\x15\x07\t**** PANIC …
=> syscalls: new panic signature

api/hw/devices.hpp, api/posix/sys/mman.h, src/kernel/os.cpp, src/kernel/softreset.cpp
- hw::Devices::flush_all()
- Soft reset preserves memory limits properly
=> Functionality required by the latest LiveUpdate

api/util/crc32.hpp, src/kernel/sanity_checks.cpp, src/kernel/softreset.cpp
- This reduces LiveUpdate time from 20ms to 11ms, so its cut by about half.
- crc32_fast() cannot be mixed with outside checksums, as it uses an Intel polynomial
=> Utilize hardware CRC32-support when possible

api/net/inet_common.hpp, api/net/port_util.hpp, api/net/tcp/tcp.hpp, api/util/fixed_bitmap.hpp, src/net/tcp/tcp.cpp, test/CMakeLists.txt, test/net/unit/dhcp_message_test.cpp, test/net/unit/port_util_test.cpp
Also fixed unittests not compiling on macOS
=> Moved Port_util to separate module + unittest

CMakeLists.txt, etc/install_dependencies_linux.sh
Fixes #1385.
Adding `BUILD_ALWAYS` does not slow down the make step if no changes have been made (which I thought it would do). It performs as I would hope where it builds again if either the output files have been deleted, or if there are changes made to the src files.
=> cmake: external projects now build always

src/platform/x86_solo5/os.cpp
When doing a `solo5_exec` we are resetting `uptime` and `micros_since_boot`. This is wrong as `micros_since_boot` should measure the time since the first boot (not the reboot due to the exec).
This change fixes that by not setting the `booted_at_` variable at every boot; instead, it leaves it at 0. This is a good approximation as `booted_at_` usually has less than 1 ms (~700000 nanoseconds).
@fwsGonzo ^^^
=> solo5: should not set booted_at to the new reboot time after a solo5_exec

src/kernel/irq_manager.cpp
This should address #1388. I am able to compile IncludeOS using the current clang SVN.
See https://stackoverflow.com/questions/12397451/why-cant-i-save-the-value-of-rip for an explanation.
=> kernel: Fix register dump of the instruction pointer on x86_64

cmake/post.service.cmake
When building services.
- `-DEXTRA_LIBRARIES` to add additional libraries
- `-DEXTRA_DRIVERS` to add additional drivers
- `-DEXTRA_PLUGINS` to add additional plugins
- `-DMEMDISK="path"` to inform CMake to build a memdisk from the folder. This takes precedence over a call to `duskbuilder()`, which will be ignored if `MEMDISK` is set.
Is it pretty? No. Does it work? Yes.
=> cmake: Support for extra defines supplied in command line

src/platform/x86_solo5/os.cpp
Some apps like tcp-perf do their work inside `Service::ready` instead of `Service::start`, so they expect a network stack at `ready`. Solo5 initialization currently calls `Timers::init` which calls `Service::ready` before initializing devices (in `Solo5_manager::init`). This change reorders that.
=> solo5: don't call timers::ready before initializing devices

api/net/ip4/addr.hpp, test/net/unit/ip4_addr.cpp
The regex had an en-dash instead of a hyphen in the character range
=> Fix IPv4 address validation

api/arch.hpp, api/kernel/irq_manager.hpp, src/kernel/irq_manager.cpp, src/kernel/profile.cpp, src/platform/x86_nano/CMakeLists.txt, src/platform/x86_nano/platform.cpp, src/platform/x86_pc/CMakeLists.txt, src/platform/x86_pc/apic_revenant.cpp, src/platform/x86_pc/idt.cpp, src/platform/x86_pc/idt.hpp, src/platform/x86_pc/pit.cpp, src/platform/x86_pc/platform.cpp, test/lest_util/os_mock.cpp
... in preparation for adding long-mode TSS, interrupt stack tables and enabling red-zone
=> x86: Move IDT and CPU exceptions to x86 IDT

src/arch/i686/CMakeLists.txt, src/arch/i686/exceptions.asm, src/arch/x86_64/CMakeLists.txt, src/arch/x86_64/exceptions.asm, src/platform/x86_pc/idt.cpp
Should get proper register output, exception number and error codes in panics now on both 32- and 64-bit
=> x86: Handle CPU exceptions, read registers properly

api/hw/cmos.hpp, src/hw/cmos.cpp
Fixes https://github.com/hioa-cs/IncludeOS/issues/1305
=> x86: Use CMOS century register to calculate year correctly

lib/LiveUpdate/liveupdate.hpp, lib/LiveUpdate/partition.cpp, lib/LiveUpdate/resume.cpp, lib/LiveUpdate/update.cpp, lib/uplink/ws_uplink.cpp, test/kernel/integration/LiveUpdate/service.cpp, test/kernel/integration/LiveUpdate/test.py, test/kernel/integration/LiveUpdate/test_boot.cpp
Also rename `register_serialization_callback` to simply `register_partition`.
Resume setup is simplified if normal execution simply returns false if there is nothing to resume.
=> lib: Make LiveUpdate::resume boolean

src/arch/x86_64/linker.ld
Force the ELF's first segment to be page aligned.
From this (from `readelf -a`):
```
Program Headers:
Type           Offset             VirtAddr           PhysAddr
FileSiz            MemSiz              Flags  Align
LOAD           0x00000000000000e8 0x0000000000a000e8 0x0000000000a000e8 <===not aligned
0x00000000002c3ecb 0x0000000000455e28  RWE    80
GNU_EH_FRAME   0x0000000000204138 0x0000000000c04138 0x0000000000c04138
0x000000000000873c 0x000000000000873c  R      4
GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
0x0000000000000000 0x0000000000000000  RWE    10
```
to this:
```
Type           Offset             VirtAddr           PhysAddr
FileSiz            MemSiz              Flags  Align
LOAD           0x0000000000000100 0x0000000000a01000 0x0000000000a01000 …
```
=> solo5: Force page-aligment for first ELF segment

cmake/cross_compiled_libraries.txt
Two changes:
- Point to solo5 master as of today, commit `f8a277f83807`.
- Don't rely on `make build` (which doesn't exist in master), and just copy solo5.o, ukvm-bin, and solo5.h by hand.
Tested with `test_ukvm.sh` on a docker container (started with `--privileged --net=host`) running Ubuntu 16.04.3 LTS and gcc 5.4.0.
cc @alfred-bratterud
=> Point to upstream Solo5

api/net/inet.hpp, api/net/inet4.hpp, api/net/ip4/packet_udp.hpp, api/net/ip4/udp.hpp, api/net/ip4/udp_socket.hpp, api/net/socket.hpp, api/net/tcp/tcp.hpp, src/net/dhcp/dh4client.cpp, src/net/inet4.cpp, src/net/ip4/udp.cpp, src/net/ip4/udp_socket.cpp, src/plugins/syslogd.cpp, src/plugins/unik.cpp, src/posix/udp_fd.cpp
For NAT MASQUERADE to work correctly, UDP needs to get it's port from the stack. Use of Port_util will avoid any conflict.
UDPSocket is now also made to bind on a specific address (default is the `stack.ip_addr()`) by using `Socket` as identifier in the collection. UDP *do not* support listening on all addresses by binding to `ANY_ADDR`, due to then we no longer know what source IP to use when using `sendto()`.
This could be solved by either:
1. Passing source addr into sendto call (not very nice and unnecessary in most cases)
2. Let the IP module set the source IP depending on destination (no idea how that algorithm would look like)
@alfred-bratterud @fwsGonzo
=> Refactored UDP to use Port_util (and more)

api/net/ws/header.hpp, src/net/ws/websocket.cpp
* make_header renamed to create_wsmsg
* Returns buffer_t with correct header length as size()
* No more raw buffers
=> net: Use refactor WebSocket header creation to be safer

stylesheets/styles.css
The font on the current website is a little hard to read. I hope you agree that this improves it a bit?
Please note that the `font-display: fallback` is only implemented in recent versions of Chrome and Firefox, but it only effects how the page looks in the brief (50-100ms) time during the page loads.
=> Makes the website homepage much more readable

api/fs/disk.hpp, api/net/ws/header.hpp, api/net/ws/websocket.hpp, examples/websocket/service.cpp, lib/uplink/ws_uplink.cpp, src/net/ws/websocket.cpp
... made possible by buffering header to its own array, and the data to a vector
Also supports partial WS header to some degree, but must receive the first two bytes in one message
Adds Message::extract_shared_vector(), although it could just be called extract data
=> WebSocket buffer extraction

cmake/cross_compiled_libraries.txt
Point to latest solo5, so to get the fix for #1540 . Just in case, the added `include`s (in latest master) are here:
https://github.com/Solo5/solo5/blob/master/ukvm/ukvm_hv_kvm.c#L32
https://github.com/Solo5/solo5/blob/master/ukvm/ukvm_hv_kvm_x86_64.c#L34
Should I create a PR for master as well?
@fwsGonzo
=> solo5: point to solo5 latest

src/net/dhcp/dhcpd.cpp
=> Removing unnecessary check of cid.empty() in dhcpd.cpp

api/net/conntrack.hpp, api/net/inet.hpp, api/net/netfilter.hpp, api/net/router.hpp, src/net/conntrack.cpp, src/net/ip4/ip4.cpp, test/net/integration/nat/service.cpp, test/net/unit/conntrack_test.cpp, test/net/unit/cookie_test.cpp, test/net/unit/router_test.cpp
Conntrack now has separate timeout values per protocol and state (any opinions on a cleaner design for options?).
Packetfilter now reverted to take ptr instead of reference. Router now has forward chain.
=> Conntrack and Router changes

src/platform/x86_solo5/os.cpp
Adding missing `__arch_time_now` implementation to solo5. This was broken after 5b90cfc277c3284c9d2b6c65f605e5bc7282eff9. Will work on something for #1521 
Question: the returned time should be in nanoseconds right?
Tested with test_ukvm.sh on an ubuntu:16.04 container.
=> solo5: add missing __arch_time_now to solo5 platform

test/misc/ukvm/test.sh
This is a new solo5 test along the lines of #1521 : "./test/misc/integration/ukvm that starts the demo service with ukvm and verifies ping / curl response".
It returns success (rc=0) and failure (rc=1) in the following cases:
1. if non-linux, it returns success (rc=0) and prints "SKIPPED".
2. linux without access to KVM returns success (rc=0) and prints "SKIPPED" if the unikernel can be built.
3. linux without access to KVM returns failure (rc=1) and prints "FAILURE" if the unikernel can NOT be built.
4. linux with access to KVM returns success and prints "SUCCESS" if the unikernel can be built, executed, and curl'ed correctly.
5. linux with access to KVM returns failure and prints "FAILURE" if the unikernel can NOT be built, or it can NOT be executed, or it can NOT be curl'ed within 30 …
=> (WIP) solo5: adding misc/integration/ukvm/test.sh

src/net/http/header.cpp
#1590 Just a small change to fix the issue opened by myself.
However, I am not sure why `field` is capture by reference in the lambda function here,
`std::find_if(fields_.cbegin(), fields_.cend(), [&field](const auto _) {`
So I didn't make a change to this line.
The `field` is a const string_view, and is pass by value to `find` function.
BTW, can someone explain how unit test is organized in this repo? There is a `lest_util` folder. Am I supposed to use it?
=> cleanup: use another std::equal function to remove verbose code

etc/scripts/grubify.sh
Only 1 of the 2 `losetup` commands had sudo before them. This created some issues in Rhel 7 when performing grubify commands.
=> Grubify: Added missing sudo to script

examples/snake/snake.hpp
Fixes the following error reported in https://github.com/hioa-cs/IncludeOS/issues/1605:
```
IncludeOS/examples/snake/snake.hpp:179:27: error: cannot call member function ‘void Snake::game_loop()’ without object
[this](auto) { game_loop(); }
```
I'm already aware that I'm not supposed to build IncludeOS with GCC. Still, I think it's beneficial to limit dependence to a specific compiler.
=> Fix GCC 5.4 compiler error (to dev)

etc/vboxrun.sh
IncludeOs now builds 64-bit images, so ostype needs updating (#1613)
=> Update vboxrun.sh to specify "Other_64" as ostype

src/drivers/e1000.cpp, src/drivers/e1000.hpp, vmrunner/vm.schema.json, vmrunner/vmrunner.py
```
* CPU was 32.09% idle
Packets RX [178243] TX [370768]
Duration: 2.68s - Payload: 512/512 MB - 1528.42 MBit/s
```
=> e1000 optimizations

api/hw/ps2.hpp, api/util/ringbuffer.hpp, cmake/cpu_feat.cmake, examples/snake/service.cpp, src/drivers/CMakeLists.txt, src/drivers/vga_emergency.cpp, src/hw/ps2.cpp, src/kernel/syscalls.cpp, src/platform/x86_nano/platform.cpp, src/platform/x86_pc/apic.cpp, test/lest_util/os_mock.cpp, test/util/unit/ringbuffer.cpp
New driver: vga_emergency
- Does not need the vga output driver to work and uses no heap
- Logs to 128k ringbuffer
- Re-activates interrupts on panic and enables keyboard handler
- Prints partial VGA buffer based on position in buffer
- Navigate up and down the OS log while in panic!
=> Emergency VGA logbuffer driver 

diskimagebuild/filetree.cpp
Instead of getting 
```
Unable to enter directory /Users/ingve/IncludeOS/examples/webtest/disk1/public/info
```
which leaves you none the wiser as to why, you now get
```
Unable to enter directory /Users/ingve/IncludeOS/examples/webtest/disk1/public/info: Permission denied
```
=> diskimagebuild: add more diagnostic output for errors

lib/uplink/ws_uplink.cpp
Simple addition that makes reboot option reports correctly in mothership.
=> Cherry-pick master: Uplink: Sending uplink with reboot option

lib/uplink/ws_uplink.cpp, src/net/http/client_connection.cpp
To avoid panic if the request has timed out and the response is received after this
=> HTTP client_connection.cpp: Replacing Ensures(on_response_) with if statement

api/net/ws/websocket.hpp, lib/uplink/ws_uplink.cpp, lib/uplink/ws_uplink.hpp, src/net/ws/websocket.cpp
Bandaid for when timers are broken.
=> uplink: No longer delay liveupdate, but instead flush

etc/install_dependencies_linux.sh
With "export CC=/usr/bin/clang-3.8" and actually installed clang-3.8,
we failed to request at least 5.0 version.
The "export CC=" line was added as install.sh suggested, so I
guess it is quite common case.
Signed-off-by: Justin Cinkelj <justin.cinkelj@xlab.si>
=> etc: ensure (already installed) clang is at least 5.0

src/net/ip4/udp.cpp
UDP process_sendq: Only writing if something is remaining.
UDP write: Expecting that something is remaining and only transmitting if chain_head != nullptr.
Solves #1701
=> Updating logic related to processing of UDP packets

etc/boot, test_ukvm.sh, vmrunner/vmrunner.py
Changes done:
- The IncludeOS can now be booted on solo5 as follows
`boot --with-solo5 .`
- Changed test_ukvm.sh to reflect this change.
- vm.json file is not required for solo5 currently but can be used if required in the future.
-  Created a new class ukvm under hypervisor
- Moved start_process() function to the parent class(hypervisor). Similarly, stop(), wait() and other functions could be moved to the parent class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1706)
=> Allow booting of solo5/ukvm with the boot command

examples/UDP_perf/CMakeLists.txt, examples/UDP_perf/README.md, examples/UDP_perf/config.json, examples/UDP_perf/docker_run.sh, examples/UDP_perf/receive.sh, examples/UDP_perf/send.sh, examples/UDP_perf/service.cpp, examples/UDP_perf/vm.json, examples/UDP_perf/vmw.sh
Changes done:
- Runs a udp server or a client as a IncludeOS unikernel
- When run as a server, sample is calculated every 5 seconds. 
- When run as a client, a bunch of packets is sent every second for default 10 seconds. Need to pass "client" argument to the program to run it as a client.
- Uses ncat to send and receive packets. 
- Works with Qemu for now. With ukvm, there is a timing issue resulting in samples not being collected correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1707)
=> Udp performance test

api/net/buffer_store.hpp, api/util/isotime.hpp, src/net/buffer_store.cpp, test/CMakeLists.txt, test/lest_util/stdlib.h, test/util/unit/isotime.cpp
Building unittest on mac now uses brew bundled libc++. The user still has to export correct CC/CXX for it to build (Apple do not support c++17 on native Sierra 10.12.6).
isotime now checks the return value from strftime and return empty string if something is wrong. #1721
Bufferstore now using aligned_alloc instead of memalign (supposedly better and less mocking for mac unittest). Also replaced `next_` with unique_ptr due to some weird missing stuff on mac. The problem didnt go away but the error was cleaner. 
What fixed the problem was using brew bundled libc++.
=> Fixed unittest on mac + isotime issue

vmrunner/vmrunner.py
When I tried to run IncludeOS with solo5 with `boot --with-solo5 .`  I got the following error
```
Traceback (most recent call last):
File "/home/osboxes/includeos//includeos/vmrunner/vmrunner.py", line 855, in boot
self._hyper.boot(multiboot, debug, "booted with vmrunner", "udp_perf")
TypeError: boot() takes at most 4 arguments (5 given)
```
Looks like this because of a recent change (#1708) where the `debug` parameter was added to Qemu but not to ukvm.  I simply added the debug parameter and its a NO-OP for now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1726)
=> Fix the breakage of booting solo5 using '--with-solo5' option

lib/uplink/ws_uplink.hpp
The tag actually lives in config (see config.hpp)
=> uplink: removed unused variable

examples/UDP_perf/service.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1738)
=> UDP perf: Replace OS::nanos_since_boot() with RTC::nanos_now() to the get the timing working with solo5

src/net/tcp/tcp.cpp
Solves TCP issues in solo5, which doesn't virtualize TSC.
=> tcp: Use RTC instead of OS nano timestamp

examples/LiveUpdate/service.cpp, test/net/integration/README.md, test/net/integration/dhcpd/service.cpp
Changing IP addresses due to failed integration tests on new test workers.
The earlier network mask was more open so a larger IP range worked.
After recent change to the network mask, the dhcpd integration tests failed.
Thus changing IP address to a smaller range for the network tests.
=> Changing IP addresses for dhcpd integration test

.gitignore, etc/build_chainloader.sh, etc/install_from_bundle.sh, etc/use_clang_version.sh, install.sh
Moved code from `install_from_bundle.sh` to separate script so that it can be called multiple places.
When trying to build latest dev in a docker container I noticed that the chainloader was not built using clang as the rest of the installation process was. Every step now sets the compiler explicitly before getting called so that we know the correct compiler will be used. 
This is still not perfect:
- Installing dependencies still has a separate check for which version to install, this also differs between ubuntu and mac. 
- Do we need both `CLANG_VERSION_MIN_REQUIRED` and the lists of compatible compilers?
=> Compiler: Separate script for check/set of clang version.

test/net/integration/microLB/test.py
The `setup.sh` file installs a program called nodejs, not node.
=> test: Changed name of node process to reflect real name

src/musl/mremap.cpp
`mremap` used to return `SUCCESS` even though it's not implemented. This
results in issues for users calling `realloc`.
If we instead return `ENOSYS`, musl is able to detect that `mremap`
isn't implemented and fall back to `malloc`/`memcpy`:
https://git.musl-libc.org/cgit/musl/tree/src/malloc/malloc.c#n397
This was originally suggested by @fwsGonzo as a workaround for issues
@andeplane ran into. After having a look at musl, I think it makes sense
to do this officially too.
Note: There are a bunch of other syscalls who also return SUCCESS even
though they're stubbed out. Whether it makes sense to do the same to
them has to be evaluated case by case taking the effect on the rest of
the system into consideration.
=> mremap: Be honest about not being implemented

CONTRIBUTE.md
The old link was to a wiki that seems to no longer exist. In README.md,
I found a link to the contribution guidelines on readthedocs, so I
assume that's the one we want to use.
=> CONTRIBUTE.md: Fix link to contribution guidelines

test/net/integration/dhcpd/vm.json
Without time sensitive, the test often times out or fails.
=> Net: Adding dhcpd test to time senstive.

src/service_name.cpp
Moved `extern "C"` to correct location. Otherwise, when executing `./test_ukvm.sh` the following compile error is generated:
```
includeos/src/service_name.cpp:24:8: error: expected unqualified-id before string constant
extern "C"
^
```
=> Fix compile error when using test_ukvm.sh

test/kernel/integration/grub/setup.sh, vmrunner/prettify.py
Gone are the days of light gray on white background. 
By just using standard `print` most terminals invert the output to black/white based on their own color scheme.
=> Test: More readable stderr output in testrunner

test/README.md, test/net/integration/dhcpd/service.cpp, test/net/integration/dhcpd/setup.sh
An attempt to increase the stability of this test. Locally on my mac the arp cache was causing all sorts of problems.
=> Test dhcpd: Add flushing of arp cache for addresses used in test

test/net/integration/icmp6/setup.sh
will output errors if there are any, otherwise quiet.
=> net/icmp6: silencing the output from ipv6 command

api/hw/nic.hpp, api/net/inet.hpp, api/net/link_layer.hpp, api/net/vif.hpp, cmake/linux.service.cmake, linux/src/drivers/usernet.cpp, linux/src/drivers/usernet.hpp, src/drivers/e1000.cpp, src/drivers/e1000.hpp, src/drivers/solo5net.cpp, src/drivers/solo5net.hpp, src/drivers/virtionet.cpp, src/drivers/virtionet.hpp, src/drivers/vmxnet3.cpp, src/drivers/vmxnet3.hpp, test/lest_util/nic_mock.hpp, test/linux/websockets/run.sh, test/net/integration/tcp/service.cpp
The public APIs never used the bufferstore, and the drivers tended to accidentally use a virtual call to its own bufferstore.
=> Decouple bufferstore from public APIs

cmake/nacl.cmake
In NaCl.py we now create a NaCl_state object containing all the state (dictionaries, lists).
The subtranspilers folder and type_processors folder are scanned and each file's init function is called from NaCl.py's main function.
After the registration of the type_processors and subtranspilers, the NaCl file given as input to NaCl.py is visited (antlr), and all identified NaCl elements are registered in the NaCl_state object's elements dictionary.
NaCl.py's handle_input function is then called, which loops through all the registered elements and call each element's process() method, which transpiles and registers the element's values in the NaCl_state object's pystache_data dictionary. This dictionary is then given as input to the cpp_template.mustache file, which contains the template for …
=> Updating NaCl (new dynamic implementation)

api/net/tcp/stream.hpp, api/util/delegate.hpp, test/util/unit/delegate.cpp
Checking if this breaks anything. Not sure if it has any side effects to make the destructor_ptr to nullptr, since the destructor of the inplace delegate checks if it exists before calling it. This will kinda fix #1821, but this is only for the inplace type. Could be that it's necessary to create custom move construct & assignment for the other types as well.
=> Delegate changes

lib/uplink/CMakeLists.txt, lib/uplink/config.hpp, lib/uplink/log.hpp, lib/uplink/uplink.cpp, lib/uplink/uplink.hpp
```
#include <uplink/uplink.hpp>
void Service::start() {
auto& link = uplink::get();
}
```
Works together with plugin (only instantiated once).
=> uplink: Install headers and make instance retreivable from service

api/net/dhcp/dh4client.hpp, src/net/dhcp/dh4client.cpp, src/net/inet.cpp
By supplying timeout = 0, DHCP will now continue forever.
I added to constants that can be tuned:
```
static constexpr std::chrono::seconds RETRY_FREQUENCY{1};
static constexpr std::chrono::seconds RETRY_FREQUENCY_SLOW{10};
```
There is also hardcoded that it should make 10 tries before slow face:
```
void DHClient::restart_negotation()
{
...
static const int FAST_TRIES = 10;
// never timeout
if(tries <= FAST_TRIES)
{
// do fast retry
timeout_timer_.start(RETRY_FREQUENCY);
}
else
```
Fixes #1716. Inet still got default timeout to 10 seconds (also not using std::chrono), same if nothing is supplied in config.json. For it to work, config.json needs the field `timeout: 0` to try forever.
So i guess that's todo/decision to be made what the default should be.
=> Let DHCP continue forever if no timeout

api/net/packet.hpp, api/util/statman.hpp, lib/uplink/ws_uplink.cpp, linux/src/main.cpp, linux/src/os.cpp, src/CMakeLists.txt, src/util/statman.cpp, src/util/statman_liu.cpp, test/kernel/integration/LiveUpdate/test_boot.cpp
- Overwrites stats with stats from previous system
- Uplink serializes stats by default
- Counts system updates (system.updates)
- No API or uplink protocol changes
=> Serialize statman, preserving stats

etc/boot, vmrunner/vmrunner.py
This change makes vmrunner use the config drive filename as the argument for solo5/ukvm's `--disk`. With this we can now run FS unikernels easier, like:
```
cd test/fs/integration/fat32
boot --with-solo5 .
```
=> Adding boot and vmrunner support for solo5 disks

cmake/cross_compiled_libraries.cmake, src/drivers/solo5blk.cpp, src/drivers/solo5net.cpp, src/platform/x86_solo5/kernel_start.cpp, src/platform/x86_solo5/os.cpp
This is mainly for #1515 as solo5 version (0.3.0) has a fix for it. The solo5 interface changed slightly for 0.3.0 like function names, and args to `solo5_app_main` and the block ones (offsets are now bytes and not sectors anymore). All changes were straightforward except `src/drivers/solo5blk.cpp`: might not be doing the right thing with the smart pointers used for buffers (specially how to release them on error).
Tested with `tetst/misc/ukvm/test.sh` and `test/fs/integration/fat32` on an `Ubuntu 16.04` using clang 6.0.
=> Point dev solo5 to v0.3.0

vmrunner/vmrunner.py
The latest changes to solo5 hypervisor module broke support for demo_example (and other FS-less services). This is the fix.
=> vmrunner: Support solo5 instances without disks

CMakeLists.txt, api/kernel/timers.hpp, cmake/post.service.cmake, examples/TCP_perf/CMakeLists.txt, examples/TCP_perf/service.cpp, src/drivers/solo5blk.cpp, src/kernel/timers.cpp, src/platform/x86_solo5/os.cpp, test/fs/integration/virtio_block/CMakeLists.txt
Event loop now waits for next timer, when one is present, otherwise tick 500ms (change in solo5/os.cpp). Since all normal services use timers, the end result is a tickless kernel. Previously the kernel ticked every 0.5 milliseconds, which was overmuch.
=> solo5: Make event loop tickless

cmake/cross_compiled_libraries.cmake
Point to latest solo5 master as of Aug 1st (285b80a). The difference between 0.3.0 (where includeos is currently pointing to) and 285b80a is minor fixes (including #1515).
Tested with `test/misc/ukvm` and `test/fs/integration/fat32` on an Ubuntu 16.04 using clang 6.0 and gcc 5.4.0.
=> Point to solo5 285b80a

api/arch/x86/paging.hpp, test/kernel/unit/memory.cpp
Fixes a bug where mem::protect would some times not protect the full range, and potentially remap one of the pages being protected
=> paging: fix bug in protect + regression test

api/fs/vfs.hpp, lib/LiveUpdate/serialize_tcp.cpp
It's not exception safe to do this,
```cpp
vector<unique_ptr<T>> v;
v.emplace_back(new T());
```
as `emplace_back` could cause a leak of this pointer if it throws a exception before emplacement (e.g. not enough memory to add a new element)
=> refactor emplace back

linux/src/drivers/tap_driver.cpp
Called `new` in constructor
```cpp
new epoll_event;
```
but didn't release the resource in destructor.
=> fix new without delete

api/net/tcp/common.hpp, api/net/tcp/read_buffer.hpp, api/net/tcp/read_request.hpp, api/net/tcp/sack.hpp, api/net/tcp/tcp.hpp, api/util/alloc_buddy.hpp, api/util/uri.hpp, lib/LiveUpdate/serialize_tcp.cpp, src/net/tcp/connection.cpp, src/net/tcp/read_buffer.cpp, src/net/tcp/read_request.cpp, src/util/uri.cpp, test/net/unit/tcp_read_buffer_test.cpp, test/net/unit/tcp_read_request_test.cpp, test/util/unit/uri_test.cpp
Some changes how to TCP read buffer size is set.
For now, size into `on_read(size, ...)` is ignored. This is now set on the TCP instance per interface with `set_min_bufsize()` and `set_max_bufsize()`. Min bufsize is now the amount of bytes reserved in the read buffer to start with, and max bufsize is the limit on how big the read buffer can grow.
`on_read` signature still needs to be refactored (removing the number). This is done in the next PR.
Also fixed a small, but critical, bug in SACK.
=> TCP read buffer size

examples/http_client/service.cpp
`net/super_stack.hpp` and `net/ip4/ip4.hpp`are already included via `net/http/client.hpp`
=> examples: remove unneeded includes from http_client service example

src/kernel/terminal.cpp, src/plugins/unik.cpp
> Optimize calls to std::string::find() and friends when the needle passed is a single character string literal. The character literal overload is more efficient.
Runs clang-tidy over the compilation database. 
I may push more changes from clang-tidy results.
=> clang-tidy performance-faster-string-find

api/hw/nic.hpp, api/net/buffer_store.hpp, src/drivers/e1000.cpp, src/drivers/solo5net.cpp, src/drivers/virtionet.cpp, src/drivers/vmxnet3.cpp, src/drivers/vmxnet3.hpp, src/net/buffer_store.cpp, test/lest_util/nic_mock.hpp, test/lest_util/packet_factory.hpp, test/net/integration/bufstore/service.cpp, test/net/unit/bufstore.cpp, test/net/unit/packets.cpp
- Greatly simplifies bufferstore
- Chaining removed, replaced with internal pools that can grow
- Growth can be disabled by overriding a private function
=> net: BufferStore now uses internal pools instead of a chain

src/drivers/vmxnet3.cpp
A minor correction for the sendq_dropped stat
=> vmxnet3: Use chain_length() for sendq_dropped stat

api/util/statman.hpp, linux/src/os.cpp, src/platform/x86_pc/kernel_start.cpp, src/platform/x86_pc/os.cpp, src/platform/x86_solo5/os.cpp, src/util/statman.cpp, src/util/statman_liu.cpp, test/kernel/integration/LiveUpdate/test_boot.cpp, test/kernel/integration/LiveUpdate/vm.json, test/lest_util/os_mock.cpp, test/util/unit/statman.cpp
- Use standard deque
- Remove max capacity, making it dynamic
- Make serialization more C++
=> statman: Refactor and simplify to use std::deque

api/hw/devices.hpp, api/net/super_stack.hpp, etc/scripts/create_bridge.sh, lib/uplink/ws_uplink.cpp, src/net/configure.cpp, src/net/super_stack.cpp, test/net/unit/super_stack.cpp, vmrunner/vmrunner.py
With this small change, `vm.json` now supports the `scripts` member in `net`, which means qemu can use another ifup/ifdown script than the default one (`/includeos/scripts/qemu-ifup`).
The `create_bridge.sh` already (kinda) supported creating your own custom bridge, but now you also need to assign a mac address so you can have them different.
Usage:
`$ ./create_bridge.sh bridge44 10.0.1.1 255.255.255.0 c0:ff:0a:00:00:01`
Then I copy the `qemu-if*` scripts to `~/dev/bridge44/`, and edit the `BRIDGE` value inside the scripts to `bridge44`. Executable permission also needs to be set:
`$ chmod +x ~/dev/bridge44/qemu-if*`
In `vm.json` I point to the script path (they have to be named the same):
```
"net" : [
{"device" : "vmxnet3", "mac" : "c0:01:0a:00:00:aa", "scripts": …
```
=> Support multiple bridges with qemu + simplification of Nic by MAC

api/kernel/os.hpp, api/util/bitops.hpp, lib/LiveUpdate/os.cpp, src/kernel/heap.cpp, src/kernel/os.cpp, src/kernel/syscalls.cpp, src/musl/mmap.cpp, src/net/buffer_store.cpp, test/lest_util/os_mock.cpp
This is supposed to prevent the heap from allocating memory inside the liveupdate area and better handle situations where the IP stack runs out of memory. There's also a new function that will report total memory usage including reserved areas, used here by panic to give a better idea of how close we are to actually being out of memory.
=> kernel: separate liveupdate from heap, improve OOM handling

api/util/alloc_buddy.hpp, test/util/unit/buddy_alloc_test.cpp
This is mainly fixes for the tests.
Fixes an off-by-one in the test for buddy allocator. Also takes overbooking into account when reporting "empty()" and "highest_used()". E.g. before this fix, if the allocator had attempted to allocate into the overbooking area empty would return false, even though no real allocations had happened, and "highest_used()" would falsely report that it had allocated into that area.
=> Minor fixes to buddy allocator

api/net/link_layer.hpp, lib/mana/include/mana/components/dashboard/components/statman.hpp, linux/userspace/CMakeLists.txt, src/CMakeLists.txt, src/kernel/syscalls.cpp, src/net/packet_debug.cpp
```
Assertion failed: false (/Users/andreas/dev/IncludeOS/examples/demo_service/service.cpp: operator(): 122)
**** PANIC ****
CPU: 0, Reason: TKILL called
Heap is at: 0x837000 / 0x7fdffff  (diff=125472767)
Heap area: 3140 / 125671 Kb (allocated 2360 kb)
Total memory use: ~6% (7819264 of 134086656 b)
*** Found 1 plugin constructors:
Plugin: register_autoconf_plugin() (0x206cc0)
*** Last packet:
Buffer: Begin: 0x7cd038 End: 0x7cd245 Size: 525
Layer: Recorded: 0x7cd042 Current: 0x7cd050 (14b offset)
Size: 501 Capacity: 501 Data end: 0x7cd245
Ethernet type: 0x8 IPv4
Payload 74 bytes from recorded layer begin (0x7cd042):
c0010a00002ac0010a0000010800450001f500004000400624f50a0000010a00000eea6100506a692491706b263a801810157c6700000101080a2d0878d25bb21021474554202f204854
*** Backtrace:
[0] …
```
=> Print last packet on panic

.dockerignore, .gitignore, Dockerfile, etc/docker_entrypoint.sh
Clean up dockerignore file. Clean up entrypoint script for docker. Add some useful ignores to gitignore.
Store both original IncludeOS `git describe` output and the custom tag.
=> Dockerfile and gitignore additions

api/arch.hpp, api/arch/x86_64.hpp, src/drivers/vmxnet3.cpp
Added a read ahead barrier to prevent desc.len from beeing read before its set.
=> Add memory read barrier to prevent speculative execution error

cmake/post.service.cmake
Some flavors of Linux is moving to using python3 as default python hence executing python to get python2 fails this fix helps cmake locate the correct python interpreter it should be future proof for cmake 3.12+ which includes findpython2 and findpython3 packages
=> Na cl find python fix

etc/scripts/create_bridge.sh
`[[ ]]` -> `[ ]`
This script needs a bit of reworking. It's very messy.
=> Create_bridge: Remove double parantheseses as they are not sh compatible

vmrunner/vmrunner.py
Removed the dependency on python-magic as its different on different flavors of Linux causing unnecessary confusion and frustration 
file should however work on all flavors mac and Linux at a small execution cost
A nicer yet more comprehensive fix would be to wrap the c library libmagic manually using ctags 
Also removed --preserve-env as this feature depends on the sudo/selinux configuration this needs to be tested but bugsquash runs in qemu kvm without it. 
if we are keeping --preserve-env we need to test it and notify the user why and what to do as it does not fail gracefully
=> run: some fixes to vmrunner

test/fs/integration/fat32/test.py, test/fs/integration/ide/test.py, test/fs/integration/ide_write/test.py, test/fs/integration/vfs/test.py, test/fs/integration/virtio_block/test.py, test/net/integration/dhclient/test.py, test/net/integration/dhcpd/test.py, test/net/integration/dhcpd_dhclient_linux/test.py, test/net/integration/dns/test.py, test/net/integration/icmp/test.py, test/net/integration/router/test.py, test/posix/integration/syslog_plugin/test.py, test/stress/test.py
#1931
Adding subprocess32 and thread_timeout where `subprocess_calls` seemed large and required a timeout that matches the test timeout.
A `thread_timeout` parameter has been added to assign a timeout for each test and use for two purposes so far.
For example,
-  the `boot(50)` where the `50` was the timeout has been replaced by `boot(thread_timeout)` 
- the subprocess call has been edited to use subprocess32 with a timeout as follows:
subprocess.check_output(["sudo", "hping3", "10.0.0.45", "-d", "20", "-0", "--ipproto", "16", "-c", "1"])
replaced with:
`subprocess32.check_output(["sudo", "hping3", "10.0.0.45", "-d", "20", "-0", "--ipproto", "16", "-c", "1"], timeout=thread_timeout)`
Thirteen (13) `test.py` files have been modified:   
**fs/integration/:**
fat32/test.py
ide/test.py …
=> test: changes in process threads- Adding subprocess32 and thread_timeout

test/net/integration/dhcpd_dhclient_linux/test.py
An `UboundLocalError` error was created due to adding `thread_timeout` in some subprocess calls (unnecessary use of subprocess32 call).
Removing the thread_timeout fixed the error:
```
Traceback (most recent call last):
File "/home/ubuntu/IncludeOS/vmrunner/vmrunner.py", line 861, in trigger_event
res = func(line)
File "test.py", line 122, in run_dhclient
timer.cancel()
UnboundLocalError: local variable 'timer' referenced before assignment
```
=> test: fixing dhcpd_dhclient_linux timer error created earlier

CMakeLists.txt, diskimagebuild/CMakeLists.txt, src/musl/brk.cpp, src/musl/mmap.cpp, vmbuild/CMakeLists.txt
Changes made to main CMakeLists.txt that can cause breakage 
You no longer have to pass CMAKE_INSTALL_PREFIX if your INCLUDEOS_PREFIX is set in environment 
vmbuild and diskbuilder cmake has gotten some hardening to ensure that there is a c++14 capable compiler in the env they are executing. 
The linkage to stdc++ is also added as it fixes issues with old cmake.
=> Fixes to Cmakefiles and a minor removal of some old printk's

api/net/inet.hpp, api/net/ip6/addr.hpp, api/net/ip6/slaac.hpp, api/net/ip6/stateful_addr.hpp, src/net/inet.cpp, src/net/ip6/slaac.cpp, test/net/unit/addr_test.cpp
* Supply token instead of alt addr.
* May force to use token instead of eui64 generated from MAC.
* Configuring global address is now also on a timer.
DAD is still not working correctly (for link local). This is due to NDP RFC being long and boring.
=> Ip6: Improve SLAAC

CMakeLists.txt, test/util/unit/buddy_alloc_test.cpp
So the issue was `project()` being defined before set `CMAKE_TOOLCHAIN_FILE`. When doing this toolchain is not respected, so the wrong compiler is used (WITH_SOLO5 isn't turned off).
I also had to avoid checking for c++17 support when building on Apple. This is the same reason that `set(CMAKE_CXX_COMPILER_WORKS 1)` in the toolchain file is done - CMake is trying to compile and do tests which doesn't work because of reasons. I think the reasons are because it's compiling macOS stuff which it then tries to link with binutils ld. But maybe someone knows more than me on this.
=> build: Reorder stuff to fix things building on macOS

src/platform/x86_pc/boot/bootloader.asm
Having read the bootloader, I found a very little typo in the comments.
This is confirmed by the documentation, for instance here : https://wiki.osdev.org/CPU_Registers_x86
=> x86: typo in bootloader

api/hw/nic.hpp
Should somebody ever find themselves replicating the crash we have seen, then try this commit and see what happens. It will tells us if the condition happens only during initialization, and then we can deal with it from there.
=> nic: Silently return when nobody subscribes to the TQA event

src/hw/ps2.cpp
Extended scancodes also need to have their pressed-state checked
=> ps2: Fix pressed-state for directional keys

api/hw/mac_addr.hpp, api/net/ip6/ndp/message.hpp, api/net/ip6/packet_icmp6.hpp, src/net/ip6/ndp.cpp, src/net/ip6/slaac.cpp
Now replying to neighbor solicitation when sent from unspecified source, which is used when doing Duplicate Address Detection (DAD) when doing stateless autoconf (SLAAC).
By running IncludeOS on two instances having them ask for the same IP using the newly implemented token solution, I can now see the second autoconf fail.
=> Ip6: NDP improvements

conan/http-parser/conanfile.py, conan/uzlib/2.1.1/conanfile.py, src/CMakeLists.txt, test/CMakeLists.txt, test/fs/unit/memdisk_test.cpp, test/kernel/unit/service_stub_test.cpp
Fixed code coverage
#run cmake
cmake -DCOVERAGE=ON <path>/test
#run tests
make test run
#generate coverage
make coverage
#open the html/index.html in a browser to view the code coveage
Need lcov and genhtml installed.
=> Code coverage report generation

src/arch/x86_64/paging.cpp
In some test cases on linux the commented out Expects failed as we do not control the heap
=> tests: fixed failing test in unittest future dept

conan/vmbuild/conanfile.py
`GSL` version compiled for conan branch is now `2.0.0`
=> conan: changing GSL version to 2.0.0 for vmbuild in conanfile.py

README.md
Update README to link to slack instead of gitter.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
=> Update chat link to point to slack

Jenkinsfile
Will leave a link to the coverage reports in every PR.
http://vaskemaskin.includeos.org:8080/coverage_includeos/
Here are the currently uploaded coverage reports.
=> Jenkins: Upload code coverage HTML output and comment with link

.dockerignore, Dockerfile
Does not cache any IncludeOS version, but inits conan with our config and contains the build tools (clang and nasm) required for building.
=> Dockerfile: Simplified dockerfile that works for conan workflow

src/arch/i686/linker.ld, src/arch/x86_64/linker.ld
Removed the need to have the ARCH in path to libraries. This makes it easier to create custom drivers/plugins/etc in conan for multiarch
=> build: removed ARCH as part of the path to libraries/drivers/plugins/etc

CMakeLists.txt, conanfile.py, layout.txt
added layout.txt using jinja2 to parse the build folder correctly 
we can consider making multiple in the future.
using this code the following should work 
This is a bit of fiddling initially 
git clone git@github.com:hioa-cs/IncludeOS.git
cd IncludeOS
comment out the version in the `conanfile.py`
`#version = get_version()`
(hopefully conan fixes that annoying issue)
edit `layout.txt` (jinja2 syntax) and set your build folder in the first line
{% set build_dir='build' %}
[bindirs]
cmake
[includedirs]
api
[libdirs]
{{ build_dir }}/plugins
{{ build_dir }}/drivers
{{ build_dir }}/lib
[resdirs]
{{ build_dir }}
Make sure to adjust the version to whatever is apropriate (never than latest)
`conan editable add . includeos/0.15.0@includeos/test --layout=layout.txt`
Change this to whatever build …
=> editable: one step closer

Jenkinsfile, conanfile.py, lib/LiveUpdate/conanfile.py
Needed a bit of a trick to get the correct upload CHANNEL configured. 
All 3rd party dependencies will now use the stable channel. The remote has been changed in the conan_config repo. 
New behavior is:
- PRs are not uploaded anywhere (this is same as before)
- Merges to master/dev will get uploaded to `includeos/latest`.
- Tags/releases will upload to `includeos/stable`.
=> Preparing for release. Stable 3rd party dependencies + stable/latest uploads

src/chainload/conanfile.py
I think it makes sense to use `major_mode` for this package as well.
I had to change the dependency on `vmbuild` to a hard-coded channel. It does not make sense to have transitive dependencies for that one.
=> Conan: Updated chainloader to use major_mode + new python_requires git

src/platform/x86_pc/rand.cpp
=> x86: Add missing returns in RNG init, and fail avoid TSC with solo5

README.md
I've added a suggested quick start guide for the service- and kernel workflows to the top of the readme now. I haven't updated the rest of the readme yet, but I'm wondering if some of @staiyeba's details should be moved to the external docs or if we want to keep them here. @MagnusS let me know what you think. @KristianJerpetjon great if you can verify that the quick-start guide is correct and also works for linux distros.
=> Conan quick start

README.md, src/chainload/conanfile.py, test/integration/conanfile.txt
All upstream deps have been tagged and are available in the `stable` channel.
=> Conan: Use stable versions of upstream deps

test/fs/integration/fat32/test.py, test/fs/integration/ide/test.py, test/fs/integration/ide_write/test.py, test/fs/integration/vfs/test.py, test/fs/integration/virtio_block/test.py, test/net/integration/dhclient/test.py, test/net/integration/dhcpd/test.py, test/net/integration/dhcpd_dhclient_linux/test.py, test/net/integration/dns/test.py, test/net/integration/icmp/test.py, test/net/integration/router/test.py, test/stress/test.py
Tests updated:
**fs/integration/**
* fat32/test.py
* ide_write/test.py
* ide/test.py
* vfs/test.py
* virtio_block/test.py
**net/integration/**
* dhclient/test.py
* dhcpd_dhclient_linux/test.py
* dhcpd/test.py
* dns/test.py
* icmp/test.py
* router/test.py
**stress/**
* test.py
**What I did:**
- removed `import subprocess32` and ensure `import subprocess` is present
- replaced all `subprocess32` calls with `subprocess` calls and ensure the function calls exist/works.
ref: https://docs.python.org/3/library/subprocess.html
- verified the syntax with `python -m compileall test`
PR to Upstream/dev will now run the network tests to ensure they work as intended.
=> upgrading subprocess calls to python3

api/os.hpp, cmake/os.cmake, src/kernel/os.cpp
for external libraries and drivers to work --whole-archive was missing..
To get a hold of is_booted() the function was needed in os.hpp/os.cpp
=> uplink: fixes to make remote drivers/plugins work

Jenkinsfile, test/integration/run_test.sh, test/net/integration/dhcpd_dhclient_linux/test.py, test/posix/integration/syslog_plugin/test.py, test/posix/integration/tcp/test.py, test/posix/integration/udp/test.py
- Now all integration tests should be fully iproute2 compliant. 
- Tests now run in random order
- Print timeout variable when it triggers
=> Tests: Cleansing ifconfig from all tests

cmake/os.cmake, src/net/openssl/client.cpp
this added function in os.cmake allows you to add "standard" ceritifactes to a service
=> Bring openssl certificates into certs folder in service and fix bug in release mode with assert

Jenkinsfile
Turns out the first time we run `conan inspect` on a repo we get the following output:
```
Not
Trying
conanmanifest.txt
conanfile.py
version: 0.14.1-1184
```
So I had to do a little extra filtering.
=> Jenkinsfile: Fix for version

api/https, api/net/openssl/tls_stream.hpp, src/net/openssl/tls_stream.cpp
This bug tripped up the encrypted websockets benchmark
=> openssl: Fix stream busy depth bug

lib/LiveUpdate/CMakeLists.txt
Added after ARCH definitions:
```
set(TRIPLE "${ARCH}-pc-linux-elf")
set(CMAKE_CXX_COMPILER_TARGET ${TRIPLE})
set(CMAKE_C_COMPILER_TARGET ${TRIPLE})
```
=> LiveUpdate: Req for building LiveUpdate on MacOS

test/integration/CMakeLists.txt, test/net/integration/dhcpd_dhclient_linux/CMakeLists.txt, test/net/integration/dhcpd_dhclient_linux/service.cpp, test/net/integration/dhcpd_dhclient_linux/test.py, test/net/integration/dhcpd_dhclient_linux/vm.json
Seems the only thing wrong with the test was the missing: `server->listen();` 
No point in merging this before #2155 is merged. The test will not actually run before then.
=> Dhcpd client linux test back in business

cmake/os.cmake
This then lets you do:
```os_add_ssl_certificates(starbase "../cert.pem" "/home/user/secret_site.pem")```
Supports either relative to binary dir (where cmake is called from) or full path.
=> Cmake: Option to add additional ssl certificates

api/net/tcp/connection.hpp, src/net/tcp/connection.cpp, src/net/tcp/connection_states.cpp
FIN can now be processed later than when it was received if there are holes in the recv window.
=> tcp: Handle FIN delayed if packet loss

etc/.gitignore, etc/Vagrantfile, etc/install_on_vagrant.sh, etc/vagrant.md
=> Change vagrant box

default.nix
Sets clang as stdenv and updates to 23.11 to get `clang6Stdenv`. I used Clang 6 for now as it matches the old conan profile. 
uzlib is also patched to use $(CC) instead of gcc. Later versions have fixed this, so when we can upgrade we will not need this patch.
=> nix: Use clang as stdenv

api/hw/msi.hpp, default.nix, src/crt/quick_exit.cpp, src/kernel/cpuid.cpp, src/plugins/field_medic/fieldmedic.hpp
This fixes the `nix-build` for me. Some missing includes, and it chokes on GSL4. We can probably just fix that, but we don't need span from GSL now that it's part of the standard, so I'm making a task for that too.
=> Fix broken nix-build, might  as well go to clang7

deps/musl/default.nix
Should build a useable musl for includeos with `nix-build` from `IncludeOS/deps/musl`
=> Build musl for IncludeOS with nix and clang

default.nix, pinned.nix, src/crt/quick_exit.cpp, src/net/CMakeLists.txt, src/posix/file_fd.cpp
Thanks to @MagnusS IncludeOS now compiles with nix using musl 🎉  
And, a static nix-build of LLVM's libc++. I'm looking into whether we can link against that as-is, without rolling our own build of LLVM at all.
While we build our own musl-includeos (disabled in the most recent commit) the musl from nixpkgs is the one in use during compilation for now. See for example, this issue, now fixed, where it references `musl-static-x86_64-unknown-linux-musl-1.2.3`, which is quite recent compared to the 1.1.18 musl-includeos is pinned to.
```                                                                                                                                  
/build/source/src/crt/quick_exit.cpp:13:5: error: exception specification in declaration does not match previous declaration …
```
=> Nix static wip - part 2

vmbuild/.gitignore, vmbuild/CMakeLists.txt, vmbuild/elf_syms.cpp, vmbuild/vmbuild.cpp
This reverts commit 07ad9e23fce5962b131baab839de955678c3c7c9.
Adds back vmbuild, for easier maintanence. It was moved to a separate repo, includeos/vmbuild, but we now want to have all dependencies in one place.
I hope this will retain file history - it's a simple `git revert 07ad9e2`
=> Revert "tools: Remove vmbuild"

cmake/os.cmake, default.nix, example/CMakeLists.txt, example/src/main.cpp
It links, but we don't know if it boots yet. And it's not entirely clear if it will work since `musl-includeos` is used for linking, but musl from pkgsStatic is used for compiling. But it does contain the IncludeOS symbols such as `rock_bottom` and `_start` at the right order, and is definitely using our linker script. So it's progress. 
Note that we may want to revisit how this is done based on the discussion #2236.
=> It links! An example binary linking with IncludeOS (WIP)

default.nix, example.nix, vmbuild.nix, vmbuild/CMakeLists.txt
This adds vmbuild.nix to build the vmbuild-tools and moves the example from default.nix to example.nix.
They can be built separately with:
nix-build ./vmbuild.nix
nix-build ./example.nix
This should also remove the conflicts from #2236
=> Separate nix-file for example and vmbuild, fix conflicts

shell.nix
I've been trying to make a nix shell that can take an IncludeOS package directly from a cmake install as input, to allow fast iteration on OS features, that link into a bootable, without having to rebuild the OS every time.  
- `shell.nix` is working to the point where cmake configure step finds the right versions of libcxx, libcxxabi, liunwind and musl, but compilation doesn't pick up the right clang by default. I hack it in by defining $CXX, but then it doesn't find libcxx, so c++ includes like `<string>` are unavailable. 
- `shell_overlay.nix` is a little simpler, where the idea was to expose the paths to the link time dependencies from `pkgsIncludeOS`. It has the same result - I get to the point where I think I can link, but I can't compile the bootable binary due to missing includes. …
=> Working nix-shell - a bit convoluted but allows quick iteration.

overlay.nix
This avoids rebuilding the OS when working on in-tree packages that depend on `./default.nix`, such as `./example.nix`.
Also enables parallel building, but I'm not sure this affects build time at all.
=> Only include required files in IncludeOS nix package

chainloader.nix, cmake/os.cmake, example.nix, example/CMakeLists.txt, overlay.nix, src/chainload/CMakeLists.txt
- overlay.nix now copies libc, libcxx and friends to the IncludeOS package
- os.cmake is made responsible for finding libs inside the package
- delete library env vars from chainloader and example, no longer needed
Tested with `nix-build chainloader.nix && nix-build example.nix && boot result/bin/hello_includeos.elf.bin`
=> Package unikernel dependencies with IncludeOS

shell.nix, test/net/integration/udp/CMakeLists.txt
This makes the chainloader available inside the nix shell, and exports the env var required by `boot`. 
I first tried adding it to `packages`, but then it seems to pull in some 32-bit stuff. This might not be the perfect way to set it up either, but it works.
=> Add chainloader to nix shell

test/kernel/unit/memmap_test.cpp
std::span does't have range checking, so the test fails. This commit just disables that part of the test.
The error was introduced when we switched from GSL::span, which had range checks.
=> Fix memmap_test

api/expects
Previously some unit tests would fail on calls to EXPECTS_THROW as the OS would panic. This throws an exception instead to allow those tests to proceed without failing.
=> Throw exception if Expects/Ensures fails when UNITTESTS is set

test/CMakeLists.txt, unittests.nix
Cleans up test/CMakeLists.txt and adds valgrind and clangtidy targets. See commit messages for details.
=> tests: add new targets for running valgrind and clangtidy

shell.nix, test.sh
- Add INCLUDE_VMRUNNER export in shell.nix 
Without this change I'm unable to run the tests that require vmrunner.
- Modify test.sh to output a list of failed tests before exiting
Example output:
```
👷🧰 3 / 6 steps failed. There's some work left to do. 🛠
Failed tests:
step 4: smoke_tests
step 5.9: nix-shell --argstr unikernel ./test/kernel/integration/smp/ --run ./test.py
step 5:
step 6.1: nix-shell --argstr unikernel ./test/net/integration/bufstore/ --run ./test.py
step 6.3: nix-shell --argstr unikernel ./test/net/integration/dns/ --run ./test.py
step 6.7: nix-shell --argstr unikernel ./test/net/integration/tcp/ --run ./test.py
step 6:
```
In the script, `fail()` is also called at the end of one section if one of the substep failed. This is why both "step 5.9: ..." and "step 5: " is …
=> Minor test improvements

cmake/os.cmake, src/kernel/elf.cpp, test/kernel/integration/exception/CMakeLists.txt, test/kernel/integration/exception/test.py, test/kernel/integration/stacktrace/CMakeLists.txt, test/kernel/integration/stacktrace/service.cpp, test/kernel/integration/stacktrace/test.py, test/kernel/integration/stacktrace/vm.json, vmbuild/elf_syms.cpp
This PR adds back stacktraces with symbol information + adds tests. See commits for additional details.
The main change is adding  `__attribute__(section(".data"))` to the static struct `relocs` used to store ELF metadata to make sure it's included in the ELF .data section (not BSS). This is needed to make sure that we don't overwrite parts of it when we initialise BSS.
On boot we first load the symbol table from `.elf_symbols` and move it to a new memory location. The new location of the symbol table is stored in `relocs.syms`: https://github.com/includeos/IncludeOS/blob/v0.16.0-release/src/kernel/elf.cpp#L350
We then initialise/clear the BSS area: https://github.com/includeos/IncludeOS/blob/v0.16.0-release/src/platform/x86_pc/kernel_start.cpp#L95
This previously had the side effect of …
=> Add back ELF symbols in stacktraces, add more tests

api/arch/i686.hpp, api/arch/x86_64.hpp, api/net/buffer_store.hpp, api/smp_utils, api/util/statman.hpp, src/kernel/events.cpp, src/net/buffer_store.cpp, src/platform/x86_pc/apic_revenant.cpp, src/platform/x86_pc/apic_revenant.hpp, src/platform/x86_pc/smp.cpp, src/util/statman.cpp, test/CMakeLists.txt, test/kernel/integration/spinlocks/CMakeLists.txt, test/kernel/integration/spinlocks/service.cpp, test/kernel/integration/spinlocks/test.py, test/kernel/unit/spinlocks.cpp
TTAS spinlock implementation using C++ atomics. Implements C++11 named requirements BasicLockable, Lockable and TimedLockable.
Removes scoped_spinlock as we can now use `std::lock_guard` instead.
Updates all spinlock_t users to use the new class.
Includes unit test (w/multithreading) and integration test to check that the delays work.
This also fixes the alignment issue seen in https://github.com/includeos/IncludeOS/pull/2251#issuecomment-2305819667, as we're no longer aligning a `typedef` inside a class. I didn't add back `alignas` to the class as I'm not sure if it speeds anything up + it is Intel only. I suggest we consider adding it back if we have a concrete usecase we can benchmark.
I also removed the empty lock/unlock stubs that were added when SMP=off so now spinlocks always …
=> New spinlocks in C++ w/tests

shell.nix, test.sh, test/net/integration/slaac/test.py
Running test.sh on a new machine revealed some missing dependencies. Running
tests with `--pure` will ensure that only the nix provided packages can be used
during tests, improving reproducability. 
The qemu bridge setup instructions were also added to shell.nix for convenience.
`IncludeOS$ nix-shell`
should now make it clear how to configure the network bridge required for
integration tests to pass.
=> Run tests with `nix-shell --pure`, add / fix dependencies.

deps/lest/default.nix, shell.nix, test.sh, test/stl/integration/coroutines/README.md, test/stl/integration/coroutines/service.cpp, unittests.nix
- Moves lest to its own nix file, allowing it to be used in integration tests
- Adds a vmrunner parameter to shell.nix, for vmrunner development 
- Fixes coroutines test
- Add a new test category to test.sh, STL, that tests aspects of the C and C++ runtimes
Result of `./test.sh`: 
```
🌈✨ Everything is awesome ✨
```
=> Add STL tests

api/kernel/rng.hpp, api/smp, api/util/alloc_buddy.hpp, src/kernel/events.cpp, src/kernel/profile.cpp, src/kernel/syscalls.cpp, src/kernel/timers.cpp, src/musl/nanosleep.cpp, src/platform/x86_pc/acpi.hpp, src/platform/x86_pc/apic_revenant.cpp, src/platform/x86_pc/apic_revenant.hpp, src/platform/x86_pc/cpu_freq_sampling.cpp, src/platform/x86_pc/smp.cpp, src/platform/x86_pc/x2apic.hpp, src/platform/x86_pc/xapic.hpp, src/util/statman.cpp, test/kernel/integration/smp/service.cpp, test/kernel/integration/smp/test.py
This restores basic SMP-support. The main change is that the kernel now uses explicit spinlocks for static variables initialised with get()-methods. This is necessary after we disabled threadsafe statics (which may not have worked properly in the past, as libc wasn't initialised).
I've updated the default PMR allocator to be SMP safe and replaced most of the dynamic datastructures in SMP/APIC with PMR-versions. This avoids calls through libc, although the allocator itself could probably be made more efficient.
The SMP test now only tests for tasks running on different cores and does a malloc/stack/PMR allocation test. We don't support printf or timers from different cores yet.
Without the locks the initialisation of the SMP cores would occasionally crash and reboot or the test itself …
=> Restore basic SMP support

chainloader.nix, default.nix, example.nix, overlay.nix, shell.nix
Adds a new attribute `withCcache` that defaults to false. When enabled, a wrapper around clang/clang++ will be added to the IncludeOS build environment.
With an existing cache, this reduces the service build time to about 1/5 on my server when the kernel also has to be rebuilt.
The directory used for caching is /nix/var/cache/ccache and it has to exist with the right permissions. See overlay.nix for additional details.
To enable ccache, pass "--arg withCcache true" to either nix-build or nix-shell.
To manage the ccache, install "ccache" locally. Then "sudo ccache --dir /nix/var/cache/ccache --show-stats" will show cache statistics and "sudo ccache --dir /nix/var/cache/ccache --clear" will clear the cache.
Ccache is currently disabled on unittests and integration tests to make sure that …
=> nix: add optional ccache support

CMakeLists.txt, cmake/includeos-config.cmake.in, example.nix, example/CMakeLists.txt
Enables `find_package()` from other nix-installed packages by adding `cmake/includeos-config.cmake.in` template, which is then installed to `cmake/includeos-config.cmake` with the correct paths filled in. This avoids the cmake flags that previously had to be set manually. Updates `example.nix` to use the new method.
=> Add support for cmake find_package

chainloader.nix, example.nix, overlay.nix, shell.nix, src/chainload/CMakeLists.txt
(This PR depends on https://github.com/includeos/vmrunner/pull/37, which removes the requirement for `INCLUDEOS_VMRUNNER` and `INCLUDEOS_CHAINLOADER` from vmrunner.)
- Add vmrunner and chainloader to overlay passthru so they can be easily picked up by other packages
- Add pkgs and pkgsStatic to overlay so other packages don't have to import nixpkgs/overlay unless they have to
- Simplify shell.nix to use the new values from the overlay and remove unused environment variables
- Simplify example.nix and add a test phase to boot the VM
An IncludeOS service can now be built with a very minimal nix derivation (see updated example.nix).
bonus:
- update chainloader to use find_package
=> Make it easier to write nix files that depend on IncludeOS

api/info, api/kernel/diag.hpp, src/kernel/kernel.cpp, src/kernel/syscalls.cpp, src/platform/aarch64_vm/kernel_start.cpp, src/platform/x86_nano/kernel_start.cpp, src/platform/x86_pc/init_libc.cpp, src/platform/x86_pc/kernel_start.cpp, src/platform/x86_solo5/kernel_start.cpp, src/plugins/field_medic/diag.cpp, src/plugins/field_medic/fieldmedic.cpp, src/plugins/field_medic/fieldmedic.hpp, test/kernel/integration/osinit/CMakeLists.txt, test/kernel/integration/osinit/service.cpp, test/kernel/integration/osinit/test.py, test/lest_util/os_mock.cpp
The intention is to create a reusable pattern for kernel self tests and diagnostics that costs nothing default. We have quite a few defensive validation steps in the kernel added organically as issues have been found. Ideally a fast booting kernel should always do the correct thing without having to validate. In practice, validation is crucial. 
With this proposed setup we can optionally add a validation plugin (fieldmedic) that performs more extensive self tests after key checkpoints in the unikernel lifetime has been reached, with negligible cost in the default case (the cost of an empty function call per hook) and with zero cost when toggled off at compile time.
See commit messages for details. 
To try it out: 
```
$ nix-shell ~/IncludeOS/shell.nix --pure  --argstr unikernel …
```
=> Revive Fieldmedic plugin, add early kernel diagnostic hooks 

deps/botan/default.nix, pinned.nix
- Move pin to nixpkgs 25.05
- Botan 2 now builds without overriding the configurePhase (and fails with the previous override)
- Depends on https://github.com/includeos/vmrunner/pull/39
./test.sh tests succeed, except network tests (due to missing tap device on this host)
=> Update to nixpkgs 25.05

pinned.nix
It seems like the pinned hash for \<nixpkgs> is wrong? I'm unable to build on any machine without this change.
I have verified the sha256sum of both the tar.gz file (`130b4257b3d53bfbfea6d61fb76d4751a3989a4a09a28615ff77516a82b3924d`) and the nix derivation (`1915r28xc4znrh2vf4rrjnxldw2imysz819gzhk9qlrkqanmfsxd`) matches on three separate networks and machines.
=> update pinned hash of nixpkgs 25.04
