includeos/IncludeOS

- README.md
I have added a link and embedded screenshot from the video to the README.md file.
> Added embedded video of getting started video

- vmbuild/vmbuild.cpp
* Changed syntax usage to differentiate initialization from assignment
* Replaced usage of `std::endl` for `\n` to minimize flushes
* Avoid using a raw pointer for disk image buffer by using a `std::vector`
* Used `std::fstream` type objects to avoid manual closing of file handles
* Used C++-Style cast instead of C-Style casts
> Refactored code to use modern C++ style

- src/debug/test_disk.cpp
As before, users will need to attach a disk with the requested file: `test/smaller2.jpeg`
Only use FAT32, as FAT16 isn't tested and EXT4 is just barebones
Here is the working screenshot: http://fwsnet.net/FilesystemWebserver.png
> fs: Webserver example using image file

- api/hw/ioport.hpp
- api/hw/pic.hpp
- api/kernel/os.hpp
- src/Makefile
- src/hw/ioport.cpp
- src/hw/pic_sanos.cpp
- src/hw/pit.cpp
- src/kernel/kernel_start.cpp
- src/kernel/os.cpp
inb and outb are hardware communication things.
To be more proper, these calls are now in hw/ioport class.
> inb and outb moved from kernel/os to hw/ioport

- api/fs/disk.hpp
- api/fs/disk.inl
- api/fs/disk_device.hpp
- api/fs/error.hpp
- api/fs/ext4.hpp
- api/fs/fat.hpp
- api/fs/filesystem.hpp
- api/fs/memdisk.hpp
- src/debug/test_disk.cpp
- src/fs/ext4.cpp
- src/fs/fat.cpp
- src/fs/memdisk.cpp
- src/net/ip4.cpp
> Work on extended partitions

- api/net/tcp.hpp
- api/net/tcp_connection_states.hpp
- examples/demo_service/service.cpp
- src/net/tcp.cpp
- src/net/tcp_connection.cpp
- src/net/tcp_connection_states.cpp
Includes:
* Buffer limit
* Cleaned up Packet class
* Use of shared_ptr on Connection - more flexibility to the user
* Improved state machine
* Made example service clearer
* Improved callbacks, added missing signals.
* ... some what tried to clean up..
NOTE: Don't merge, not yet done.
> TCP Improvements

- api/fs/disk.hpp
- api/fs/disk.inl
- src/debug/test_disk.cpp
disk->auto_detect(  on_mount lambda );
> fs: Mount auto-detected partition

- api/fs/fat.hpp
- src/debug/test_disk.cpp
- src/debug/test_service.cpp
- src/fs/fat.cpp
- src/net/arp.cpp
- src/net/ethernet.cpp
- src/net/ip4.cpp
> fs: FAT16 support

- test/tcp/README.md
- test/tcp/service.cpp
- test/tcp/test.py
Now tried with qemu, is working. Added README.
> test: TCP test improvements

- etc/qemu_cmd.sh
- src/seed/Makefile
- test/STL/Makefile
- test/STL/test.sh
- test/STREAM/Makefile
- test/STREAM/run.sh
- test/UDP/Makefile
- test/crt/Makefile
- test/crt/debug/service.gdb
- test/exceptions/Makefile
- test/exceptions/debug/service.gdb
- test/exceptions/service.cpp
- test/memdisk/test.sh
- test/quick_exit/Makefile
- test/quick_exit/debug/service.gdb
- test/quick_exit/service.cpp
All the old tests should now work on both mac and linux
> Fixed old tests

- api/vga
- src/Makefile
- test/fat/fat32.cpp
- test/vga/Makefile
- test/vga/debug.sh
- test/vga/run.sh
- test/vga/service.gdb
- test/vga/test.sh
- test/vga/vbox.sh
- test/vga/vga.cpp
This completes the FAT test suite (for now)
> test: Async FAT file read

- api/hw/pic.hpp
- api/kernel/irq_manager.hpp
- src/Makefile
- src/hw/pic.cpp
- src/hw/pit.cpp
- src/kernel/irq_manager.cpp
- test/IRQ_PIC/README.md
- test/IRQ_PIC/service.cpp
The PIC-class should now better reflect the Intel 8259A / 8259A-2 1988 whitepaper
> Pic revamp

- src/kernel/terminal_disk.cpp
> term: Disk terminal services

- api/fs/fat.hpp
- src/crt/cxxabi/cxa_guard.cpp
- src/fs/fat_sync.cpp
- src/seed/Makefile
- test/fat/fat16.cpp
- test/fat/fat32.cpp
- test/term/term.cpp
.. and silence warning from cxxabi, for now
> fs: fix FAT bug

- api/hw/ide.hpp
- src/hw/ide.cpp
- src/kernel/interrupts.s
- src/kernel/irq_manager.cpp
- test/IDE/service.cpp
* The first commit adds these changes
* The second one updates the tests
> hw/ide: asynchronous reading now works properly

- CONTRIBUTE.md
* Changed the spelling from `funcitonality` -> `functionality`
> Corrected typographical error

- api/net/tcp.hpp
- examples/demo_service/service.cpp
- examples/tcp/service.cpp
- src/net/tcp_connection.cpp
- src/net/tcp_connection_states.cpp
Fixed broken examples. There is also some TCP changes with congestion control (hopefully they doesnt break everything)
#485
> Repaired broken examples (due to TCP changes)

- api/common
- api/virtio/virtio.hpp
- src/Makefile
- src/seed/Makefile
- src/virtio/virtio_queue.cpp
- src/virtio/virtionet.cpp
- test/virtio_queue/service.cpp
- test/virtio_queue/test.sh
@fwsGonzo and @RicoAntonioFelix, please review - this is a WIP, but I think you get the idea of where I'm headed. @AndreasAakesson Please test on your side (OS X) as well!
**NOTE:** One issue now is that you need to explicitly pull down the GSL submodule. I'll have to add that to the install scripts, but in the meantime:
```
~/IncludeOS $ git submodule init
~/IncludeOS $ git submodule update
```
> New virtio queue interface, using GSL span (WIP)

- api/fs/filesystem.hpp
- api/fs/memdisk.hpp
- api/hw/disk.hpp
- api/hw/disk_device.hpp
- api/hw/ide.hpp
- api/net/dns/dns.hpp
- api/net/inet4.inc
- api/net/ip4/ip4.hpp
- api/net/ip4/packet_ip4.hpp
- api/virtio/block.hpp
- src/debug/test_service.cpp
- src/fs/fat_async.cpp
- src/fs/fat_sync.cpp
- src/fs/memdisk.cpp
- src/hw/ide.cpp
- src/net/dns/dns.cpp
- src/net/ip4/ip4.cpp
- src/virtio/block.cpp
- test/tcp/service.cpp
Also adds sync_read multiple sectors for disk devices
> Work on FS to support reading multiple sectors in FAT

- test/tcp/service.cpp
- test/tcp/test.py
Will now use the Vmrunner to complete the test.
> Updated tcp test to work with Jenkins

- api/net/tcp.hpp
- api/utility/membitmap.hpp
- etc/install_osx.sh
- src/net/tcp.cpp
- test/UDP/service.cpp
* Some WIP on TCP + clean up.
* Changes to membitmap (by suggestion from @fwsGonzo)
* Updated OSX script to install llvm3.8 (clang)
* Updated UDP test to reflect changes made to IP4::addr
> Minor fixes (tcp, membitmap, build osx)

- api/net/inet4.hpp
- api/net/inet4.inc
- api/net/tcp.hpp
- src/net/tcp_connection.cpp
* Also includes adding timeout parameter to Inet for DHCP timeout.
> tcp: Various fixes

- test/validate_all.sh
Used by jenkins to only run tests that are ready to run. This means that as soon as tests are complete they will be added to jenkins.
> Added option to get only name of complete tests

- etc/create_binary_bundle.sh
- test/virtio_block/service.cpp
Added some parentheses. 
It was complaining about: 
`error: reference to non-static member function must be called;`
> Fixed Virtio_block test

- test/tcp/service.cpp
Solves #537. Also improved test output
> test: tcp test now asserts

- README.md
Simplified and updated Readme, moved additional info into wiki.
> Readme updated for 0.8

- README.md
- etc/build_llvm32.sh
- etc/install_all_source.sh
- etc/install_from_bundle.sh
- etc/install_osx.sh
- etc/prepare_ubuntu_deps.sh
- install.sh
- src/Makefile
- src/seed/Makefile
- test/bufstore/run.sh
- test/bufstore/test.py
- test/bufstore/test.sh
- test/bufstore/vm.json
- test/crt/test.py
- test/crt/vm.json
- test/quick_exit/README.md
- test/quick_exit/test.py
- test/quick_exit/vm.json
- test/timers/README.md
- test/timers/test.py
- test/timers/vm.json
- vmbuild/Makefile
LLVM issues should now be resolved. The tests that Jenkins uses for the master pipeline also passes on my clean 14.04 test machine, so in theory we should be all set (but there are ghosts in the machine)
> Release 0.8.0 (take two)

- install.sh
Will get jenkins up an running again for the master branch.
> Hotfix for install.sh. Added shebang

- api/net/ip4/packet_ip4.hpp
- api/net/tcp.hpp
- examples/demo_service/service.cpp
- src/net/ip4/ip4.cpp
- src/net/tcp.cpp
- src/net/tcp_connection.cpp
- src/net/tcp_connection_states.cpp
TCP Packet now correctly calculates it length with help from IP Packet.
Fixes bug in #565
> TCP hotfix

- examples/tcp/service.cpp
- src/memdisk/memdisk.py
Solves #460.
Haven't done anything to `etc/create_memdisk.sh` tho.
> tools: memdisk.py can now build memdisk on OS X

- seed/service.cpp
Made some functionally irrelevant, stylistic changes. Sorry, but first impressions matter. :)
> C++-ified include

- src/fs/fat_async.cpp
- src/util/async.cpp
> fs: fixed circular dependency in async next-loop (dev)

- src/fs/fat_async.cpp
- src/util/async.cpp
> fs: fixed circular dependency in async next-loop (master hotfix)

- .editorconfig
- api/sys/ctype.h
- src/Makefile
- src/seed/Makelib
- src/util/async.cpp
Added `Makelib` for building IncludeOS libraries.
> Library makefile + minor fixes

- api/fs/common.hpp
- src/fs/filesystem.cpp
- src/kernel/terminal_disk.cpp
* Added API DOC 
* Refactored methods
> Augmented file api/fs/common.hpp

- test/build/test.sh
I added this to the test directory, not sure if this is a good solution as this is a basic shell script and does not really follow the same conventions as all the other tests we have here.
> Added a test for building the examples

- src/kernel/syscalls.cpp
Not a final solution, but better than being back in 1970 all the time.
The snippet 
std::string make_daytime_string() {
time_t now = time(0);
return ctime(&now);
}
now returns "Thu Jun 30 14:37:52 2016" when cmos returns "2016-06-30T14:37:52Z". 
Previously ctime returned a time and date on Jan 1st 1970.
> Improved gettimeofday

- api/kernel/elf.hpp
- api/virtio/virtio.hpp
- api/virtio/virtionet.hpp
- src/Makefile
- src/debug/run_test.sh
- src/debug/test_service.cpp
- src/hw/apic_asm.asm
- src/hw/msi.cpp
- src/hw/pci_device.cpp
- src/hw/pci_msi.cpp
- src/kernel/elf.cpp
- src/kernel/os.cpp
- src/kernel/profile.cpp
- src/linker.ld
- src/net/buffer_store.cpp
- src/net/ip4/udp_socket.cpp
- src/virtio/virtio.cpp
- src/virtio/virtionet.cpp
Also adding an optional deferred kick implementation, but it's not recommended to use. It's very slow and it can deplete bufferstores faster than normal (immediate) kicking.
> Work on hardening virtionet and bufferstores

- examples/demo_service/service.cpp
- examples/tcp/service.cpp
- test/transmit/Makefile
- test/transmit/run.sh
- test/transmit/service.cpp
- test/transmit/test.py
- test/transmit/vm.json
.. although there is something funky going on with UDP send queue.
.. or some packets gets dropped by Linux because sending too fast.
> Transmit test now fixed up and automated

- test/memdisk/Makefile
- test/memdisk/README.md
- test/memdisk/bigdisk.cpp
- test/memdisk/bigdisk.sh
- test/memdisk/nosector.cpp
- test/memdisk/test.py
- test/memdisk/test.sh
- test/memdisk/twosector.cpp
- test/memdisk/vm.json
* Made nosector service default on make
* Facelift to services using CHECKSERT macro
* Extracted bigdisk creation to separate script
* Added test.py, chaining 3 test in one run using the same Makefile
* Added README and vm.json
> test: Made the memdisk test up to date, solving #657

- index.html
Removed details that are irrelevant to our target audience; added useful links to get potential users & contributors up to speed quickly.
> Updated copy

- api/kernel/irq_manager.hpp
- api/kernel/rtc.hpp
- api/net/dhcp/dh4client.hpp
- api/rtc
- api/utility/membitmap.hpp
- src/Makefile
- src/kernel/irq_manager.cpp
- src/kernel/os.cpp
- src/kernel/rtc.cpp
- src/kernel/syscalls.cpp
- src/net/dhcp/dh4client.cpp
- src/virtio/virtionet.cpp
- test/util/unit/membitmap.cpp
The Real Time Clock keeps the OSs time up to date without querying CMOS all the time
> Adds the RTC

- api/hw/nic.hpp
- api/net/dhcp/dh4client.hpp
- api/net/ip4/addr.hpp
- api/net/tcp/packet.hpp
- api/net/tcp/socket.hpp
- src/drivers/virtionet.cpp
- src/drivers/virtionet.hpp
- src/net/inet4.cpp
- test/net/unit/ip4_addr.cpp
- test/net/unit/tcp_socket.cpp
+ Fixes to those classes
... and fix to uninti delegate (removed it all together)
> test: Added unit test for tcp::Socket and ip4::Addr

- api/hw/nic.hpp
- api/utility/statman.hpp
- src/drivers/virtionet.cpp
- src/drivers/virtionet.hpp
- src/util/statman.cpp
- test/util/unit/statman.cpp
Changed initialization of stats to VirtioNet constructor. Stat getters returning reference instead of pointer. Statman unit test updated.
> Nic/VirtioNet and Statman

- api/kernel/irq_manager.hpp
- api/utility/statman.hpp
- src/drivers/virtionet.cpp
- src/kernel/irq_manager.cpp
- src/util/statman.cpp
- test/util/unit/statman.cpp
Also reordered VirtioNet constructor initializer list because of warning
> Added stats to IRQ_manager and Statman update

- README.md
Will temporarily break master shield until dev is merged into master.
> Updates to readme to reflect new shield tests

- etc/install_all_source.sh
> install: Change vmbuilder install order, make clean OS before make

- api/net/tcp/tcp.hpp
- src/net/tcp/listener.cpp
- src/net/tcp/tcp.cpp
Incoming connections, outgoing connections, connection attempts
> TCP and Listener: Stats

- src/net/dhcp/dh4client.cpp
- src/net/ip4/ip4.cpp
This is simply all the commits to master PRd to dev
> Changes to master also into dev

- api/kernel/irq_manager.hpp
- src/hw/apic.cpp
- src/hw/pit.cpp
- src/kernel/irq_manager.cpp
> Mask off PIT interrupt in IOAPIC when unused

- api/fs/fat.hpp
- api/fs/filesystem.hpp
- api/util/delegate.hpp
- src/drivers/virtioblk.cpp
- src/drivers/virtioblk.hpp
- src/fs/disk.cpp
- src/fs/fat.cpp
- test/fs/integration/virtio_block/Makefile
- test/fs/integration/virtio_block/image.sh
- test/fs/integration/virtio_block/service.cpp
- test/fs/integration/virtio_block/test.sh
- test/fs/integration/virtio_block/vm.json
... and update the virtioblk test slightly
> Fix virtioblk corruption bug, update fs to use delegates

- examples/snake/service.cpp
- examples/snake/snake.hpp
My design goals were:
Clean modern C++
Clean task separation
Better user experience
Better readability
No vga read
No raw loops
Little control flow change with if
No usage of rand()
> Snake example rewrite

- etc/build_binutils.sh
> install: Replaces broken binutils url

- api/kernel/os.hpp
- src/kernel/os.cpp
Note: master branch.
os.hpp/.cpp: get_cycles_total() and get_cycles_halt() update.
Needed for dashboard component cpusage to get its data.
Please review.
> (master) Update os.hpp/.cpp for includeos/acorn to run on master

- install.sh
> Support KDE neon as Ubuntu

- api/fs/memdisk.hpp
- api/hw/devices.hpp
- api/hw/drive.hpp
- api/hw/msi.hpp
- api/hw/nic.hpp
- api/hw/pci_device.hpp
- api/kernel/pci_manager.hpp
- api/net/tcp/connection.hpp
- api/net/tcp/read_buffer.hpp
- api/net/tcp/rttm.hpp
- api/net/tcp/tcp.hpp
- api/virtio/virtio.hpp
- src/drivers/virtioblk.cpp
- src/drivers/virtioblk.hpp
- src/drivers/virtionet.cpp
- src/drivers/virtionet.hpp
- src/fs/memdisk.cpp
- src/hw/pci_msi.cpp
- src/net/tcp/connection.cpp
- src/net/tcp/tcp.cpp
... and some TCP memory size optimizations
> Deactivation procedures for PCI and MSI-x

- api/posix/sys/socket.h
- src/include/udp_fd.hpp
- src/posix/udp_fd.cpp
- src/posix/unistd.cpp
- test/posix/integration/udp/service.cpp
- test/posix/integration/udp/test.py
- test/vmrunner.py
* UDP Socket buffer
* Fix to vmrunner timeout
> POSIX socket progress + other stuff

- README.md
"Fix" for #846. (I'm assuming that 1) the volume of commits to the wrong branch currently isn't totally overwhelming, and 2) that there will be a release soon(-ish) so I'm sending this to dev, but the new contributors will obviously not see the message until it turns up on master...)
> Add request to have all PRs sent to dev branch

- Vagrantfile
- test.sh does not run on Ubuntu 14.04 (See issue #889)
> Update Vagrantfile to use Ubuntu 16.04

- api/kernel/rng.hpp
- src/CMakeLists.txt
- src/Makefile
- src/kernel/os.cpp
- src/kernel/rng.cpp
- src/posix/unistd.cpp
Made @randombit's RNG PR #893 merge-able.
> System rng

- api/fs/vfs.hpp
Thanks to @ingve for pointing out this horrendous error - and for a unit test!
> vfs: allow direct decendants of root

- api/hw/pic.hpp
- api/kernel/irq_manager.hpp
- src/kernel/irq_manager.cpp
- src/kernel/rtc.cpp
- src/kernel/start.asm
- src/kernel/syscalls.cpp
- test/kernel/integration/grub/CMakeLists.txt
- test/kernel/integration/grub/README.md
- test/kernel/integration/grub/create_disk.sh
- test/kernel/integration/grub/grub/grub.cfg
- test/kernel/integration/grub/service.cpp
- test/kernel/integration/grub/test.py
- test/kernel/integration/grub/vm.json
Fixed stuff required to boot with GRUB (refreshing segment regs from GDT) and added an automated test to build and boot a grub-based IncludeOS image.
> Booting with GRUB

- api/net/http/common.hpp
- api/net/http/header.hpp
- api/net/http/message.hpp
- api/net/http/methods.hpp
- api/net/http/request.hpp
- api/net/http/response.hpp
- api/net/http/status_codes.hpp
- src/net/http/message.cpp
- src/net/http/response.cpp
- src/net/http/status_codes.cpp
* Optimize includes
* Change `Status_Code_Table` -> `Status_code_table`
* Add functionality to add a set of headers to both `Request` and `Response`
> http: Improvements to module

- etc/install_build_requirements.sh
- install.sh
I had no `lsb_release` installed on my system and `install.sh` complained the system was not supported at all.
> added check for lsb_release in install script

- vmbuild/elf_syms.cpp
see #963 and Gitter for discussion
> support for multiple SHT_STRTAB sections in ELF. fixes #963

- test/CMakeLists.txt
- test/fs/unit/path_test.cpp
- test/fs/unit/vfs_test.cpp
- test/net/unit/tcp_packet_test.cpp
- test/net/unit/tcp_write_buffer.cpp
- test/net/unit/tcp_write_queue.cpp
- test/util/unit/uri_test.cpp
Mostly signed/unsigned comparisons, but also: a trigraph! How is this still a thing?
> test: updated unit tests to fix warnings

- diskimagebuild/CMakeLists.txt
- diskimagebuild/diskimagebuild.c
(Not strictly a real PR, just trying to nudge @fwsGonzo to create a disk image builder that works for those of us building on MacOS now that everything else works there...) :)
> diskimagebuild: skeleton

- CMakeLists.txt
- api/util/percent_encoding.hpp
- api/util/uri.hpp
- src/CMakeLists.txt
- src/util/percent_encoding.cpp
- src/util/uri.cpp
- test/CMakeLists.txt
- test/util/unit/uri_test.cpp
* The underlying `uri` parser to use [http-parser](https://github.com/nodejs/http-parser)
* Queries to use `string_view` to create sub-views into the given `uri`
> uri: Optimize module

- etc/install_build_requirements.sh
More info here: http://superuser.com/questions/568967/make-pacman-does-not-reinstall-when-already-installed
> Only install packages if required on Arch Linux

- api/kernel/os.hpp
- api/kernel/service.hpp
- api/net/tcp/connection.hpp
- api/posix/sys/utsname.h
- api/sys/unistd.h
- src/CMakeLists.txt
- src/crt/c_abi.c
- src/drivers/heap_debugging.cpp
- src/hw/serial1.cpp
- src/include/kprint
- src/kernel/elf.cpp
- src/kernel/kernel_start.cpp
- src/kernel/os.cpp
- src/kernel/sanity_checks.cpp
- src/kernel/service_stub.cpp
- src/kernel/syscalls.cpp
- src/linker.ld
- src/net/tcp/connection.cpp
- src/net/tcp/tcp.cpp
- src/posix/sys/mman.cpp
- src/posix/sys/stat.cpp
- src/posix/unistd.cpp
- test/kernel/integration/kprint/service.cpp
- test/kernel/integration/kprint/test.py
.. and
* Kernel sanity checks
* kprint now works in C modules
* Make the string parameter for Service::start optional
> Changes needed to compile SQlite service

- api/util/chunk.hpp
- api/util/timer.hpp
- etc/service.cmake
- test/CMakeLists.txt
- test/util/unit/chunk_test.cpp
Also made it possible to build single unit tests with `-DSINGLE=<sources>`.
> util: Added Chunk for handling shared buffer

- etc/service.cmake
- src/boot/bootloader.asm
- src/drivers/CMakeLists.txt
- src/drivers/heap_debugging.cpp
- src/drivers/silent.cpp
- src/kernel/os.cpp
- src/kernel/sanity_checks.cpp
- vmbuild/vmbuild.cpp
.. and also add silent plugin that disables serial output
> Various fixes to make bootloaded services work again

- api/fs/fat_internal.hpp
- api/fs/mbr.hpp
- api/kernel/timers.hpp
- api/net/dhcp/dh4client.hpp
- src/fs/disk.cpp
- src/fs/fat.cpp
- src/kernel/cpuid.cpp
- src/kernel/rtc.cpp
- src/kernel/timers.cpp
- src/net/dhcp/dh4client.cpp
- src/net/inet4.cpp
DHCP now also throws exception when not initialized before calling on_config. Not sure if it's the right thing to do.
> Various fixes to compile with 64bit G++, move handlers in Timers

- api/net/http/client.hpp
- src/net/http/client.cpp
- src/net/http/connection.cpp
- test/net/integration/http/service.cpp
- test/net/integration/http/test.py
Made it more flexible (and DRY)
> HTTP Client improvements

- test/testrunner.py
- Now runs as many tests in parallell as number of cpus
- Added argument to testrunner.py which only cleans the tests
> testrunner: Dynamic number of parallell tests based on cpus

- api/fs/common.hpp
- api/fs/fat.hpp
- api/fs/vfs.hpp
- api/hw/block_device.hpp
- api/net/http/client.hpp
- api/net/inet.hpp
- api/net/tcp/connection.hpp
- api/net/tcp/write_queue.hpp
- api/util/delegate.hpp
- lib/mana/include/mana/middleware.hpp
- src/net/dns/client.cpp
- src/posix/udp_fd.cpp
- test/kernel/integration/timers/service.cpp
- test/net/integration/udp/service.cpp
- test/util/unit/delegate.cpp
Focus: minimal overhead.
Demonstration:  [old](http://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAOgFYAGQUOHCALKQBWXUqgAOBPHQDOlNK1QBXYniWYAgkoC2IAOT8TpNIdl52AeVoBhBM1rAOZkwEpSSzcWQPAFIAJgBmPFpkVg0sAGogsMdaTAB3ROwg/j1QiKiY%2BMTHQ0xDEgBPDKyc8Mjo2MwEpI0FVkJKsMzs3LqCxqKqDSiFOjYq7uyCUtlWZimmxwJy2UxaZhK4gBUMuOjmJSU4rHZgOcxEgCFq6qnrWamivYO4gCVSXdnn7m%2Bczuqnw7HTCnB5JF4QPTfbhecY5ADsVwmAE4NEpIsA4koCBoAEYAfXkxDxSxWTQAIq8IAAqLwQABuqDw6Cp7xqADZQmyoTCwoicsigSDMPTGczdsoCHFUO8sbiCQQiSTGmhaFi4oYvHFaKhMAAPQLyOIga78JGoHESTDIAjyokQVA%2BE1IrJI2X4wl4iAap1BBE%2BuFkk16WS4trIY0CzAnM4QTWJClYKjMDSsAiXIMuwUxrPzFVYzlxsIJzBJlNp3kZ0054XVzkF8lHEvJ1Ppib8pHViAgEBY9Dd2gp1geyV5gia7V6g2SkCN6NTWMJBGLwNtl23GZnBYAuKOd5KtYbeM%2B0379aNbu97urZg49h4vBUIpGnsEPsgHR4gFFRxVP0BjLdkqsIui6eozHgyCELOwIxo44qqg …
> delegate rework

- README.md
> README.md update: ../run.sh my_service option removed

- api/util/delegate.hpp
- test/util/unit/delegate.cpp
> Added alignment parameter to delegate

- etc/vmware
(only supports VMware Fusion, feel free to add other VMWare products)
> vmware: stop-gap cli tool to convert and run image in VMWare

- .travis.yml
- test/CMakeLists.txt
(osx_image: xcode8.2 = macOS Sierra,
osx_image: xcode8 = OS X El Capitan)
> test: build unittests for OS X/macOS on travis

- api/kernel/elf.hpp
- api/profile
- src/kernel/elf.cpp
- src/kernel/profile.cpp
> kernel: Make elf parser use no-heap only, update stack sampler

- api/util/delegate.hpp
- src/fs/disk.cpp
- src/fs/fat.cpp
- test/fs/integration/memdisk/twosector.cpp
Not happy about it :|
Still stability is better than minor optimization.
> Delegate empty check fix

- src/net/inet_common.cpp
Should be around 8x faster than before, because of unrolled loop that processes 8x more than before, and in addition the removal of all the add carry checks.
> net: Improve IP checksum performance

- api/net/tcp/packet.hpp
- src/arch/x86/apic.cpp
- src/arch/x86/apic_asm.asm
- src/arch/x86/gdt_asm.asm
- src/arch/x86/start.asm
- src/arch/x86/x2apic.hpp
- src/kernel/elf.cpp
- src/kernel/interrupts.asm
- vmbuild/elf_syms.cpp
... because they are marked NOTYPE and have no size
> Solves issue where some C freestanding functions are not found in ELF symbol tables

- src/kernel/softreset.cpp
- src/kernel/syscalls.cpp
Also, make panic reboot when re-entered on the same CPU
> Add optional buffer to soft-reset

- api/kernel/memmap.hpp
- lib/mana/include/mana/components/dashboard/components/memmap.hpp
- src/kernel/memmap.cpp
- test/kernel/integration/memmap/service.cpp
- test/kernel/unit/memmap_test.cpp
* Add API documentation
* Add `const noexcept` to methods that exhibit such behaviour
* Move implementation of methods that contain more than one statement to the implementation file
> kernel: Augment memmap module

- api/net/tcp/socket.hpp
* Add API documentation
* Add `const noexcept` to methods that exhibit such behaviour
> net: Augment socket module

- test/net/integration/dhcpd_dhclient_linux/vm.json
- test/net/integration/router/vm.json
- test/testrunner.py
This needs to be merged so that it can be enabled in Jenkins.  Intrusive tests that require sudo commands to modify the host system will now be run on a separate fresh vm for every pull request.
> testrunner: Added properties to tests (time_sensitive, intrusive)

- api/net/ip4/addr.hpp
* Made ip4::Addr a literal type
> net: Refactored module ip4::Addr

- api/util/base64.hpp
* Remove dependency on `gsl`
* Change API documentation comment style
> util: Remove dependency on gsl from base64 module

- api/hw/mac_addr.hpp
* Made MAC::Addr a literal type
* Add API documentation
> hw: Refactored module MAC::Addr

- CMakeLists.txt
- api/net/tcp/connection.hpp
- api/net/tcp/connection.inc
- cmake/cpu_feat.cmake
- cmake/vanilla.cmake
- etc/library.cmake
- etc/service.cmake
- src/arch/x86/start.asm
- src/net/tcp/connection.cpp
- src/net/tcp/connection_states.cpp
- test/kernel/integration/block/vm.json
- test/net/integration/tcp/service.cpp
- vmrunner/vm.cpu_feat.json
- vmrunner/vm.schema.json
- vmrunner/vm.vanilla.json
- vmrunner/vmrunner.py
> Make CPU features optional

- cmake/cross_compiled_libraries.txt
The saviour we desperately need!
> new_bundle: updated cmake to use new bundle

- api/net/dns/client.hpp
- api/net/dns/dns.hpp
- api/net/inet.hpp
- api/net/inet4.hpp
- api/util/isotime.hpp
- src/net/dns/client.cpp
- src/net/dns/dns.cpp
Had to change the API to accept `bool force`, which if true will ignore cache lookup.
> DNS client caching

- src/arch/x86/x2apic.hpp
- src/arch/x86/xapic.hpp
Doesn't fix any known issues afaik
> x86: Only iterate over 160 bits in ISR and IRR xapic/x2apic registers

- examples/acorn/service.cpp
- lib/mana/include/mana/components/dashboard/components/cpusage.hpp
This makes acorn work again after adding some more asserts in the timer system
> mana: Remove when parameter for CPUsage

- CMakeLists.txt
- api/net/http/websocket.hpp
- cmake/post.service.cmake
- src/net/http/websocket.cpp
- Disables red-zone which had problems even when stepping past it in the interrupt handlers
- Minor change to websockets
> x86_64 now stable

- api/hw/nic.hpp
- api/kernel/irq_manager.hpp
- api/net/ethernet/ethernet.hpp
- api/net/link_layer.hpp
- api/util/fixedvec.hpp
- api/util/membitmap.hpp
- api/util/statman.hpp
- lib/mana/include/mana/components/dashboard/components/statman.hpp
- src/drivers/virtionet.cpp
- src/drivers/vmxnet3.cpp
- src/kernel/irq_manager.cpp
- src/net/ethernet/ethernet.cpp
- src/util/statman.cpp
- test/lest_util/nic_mock.hpp
- test/util/unit/statman.cpp
- Adds free() to delete stats
- Keeps track of stats using bitmap
- Simplified interface, made it look more like C++ stdlib container
- Update test to reflect changes
> Updates to statman

- api/util/crc64.hpp
> util: Add crc64 module

- etc/install_dependencies_linux.sh
- install.sh
* Add installation support for https://www.parrotsec.org/
> install: Add support for Parrot Security OS

- src/arch/x86_64/arch_start.asm
- src/arch/x86_64/interrupts.asm
- src/kernel/elf.cpp
- src/kernel/os.cpp
Statman was too small with only 2 pages, and the all the cores couldn't share the same stack
> SMP now stable in x86_64

- api/util/crc64.hpp
* These mods are to support compilation on g++ as it complains about errors seen in the attached snapshot
> crc64: Modifications to support compilation on g++

- api/net/ws/websocket.hpp
- src/net/ws/websocket.cpp
> WS bandaid

- cmake/botan.cmake
- cmake/post.service.cmake
- src/kernel/multiboot.cpp
- src/kernel/os.cpp
- Also updated Botan to latest version
> Botan TLS on 64-bit

- api/kernel/os.hpp
- api/smp
- src/drivers/silent.cpp
- src/kernel/syscalls.cpp
- src/platform/x86_pc/smp.cpp
Also increase SMP max core count
> Silent start shows panic() messages

- api/crash
- api/kernel/syscalls.hpp
- api/smp
- api/smp_utils
- src/CMakeLists.txt
- src/kernel/os.cpp
- src/kernel/syscalls.cpp
- src/kernel/tls.cpp
- src/linker.ld
- src/platform/x86_pc/apic_revenant.cpp
- src/platform/x86_pc/gdt.hpp
- src/platform/x86_pc/platform.cpp
- src/platform/x86_pc/smp.cpp
- test/kernel/integration/smp/test.py
- TLS
- GS cpu / FS thread
- SMP support for panic context buffers
- Unrelated to exception support on SMP
> Thread Local Storage

- etc/install_from_bundle.sh
- install.sh
Useful for installation with docker
> Install: option to disable bridge install

- api/util/crc32.hpp
- src/posix/pthread.cpp
A good bit faster than just 1 byte at a time.. unfortunately, I was not able to figure out the 64-bit intrinsic, so to make this even faster might have to restort to inline assembly. This is most likely a 3-4x speedup.
> util: Optimize hardware crc32 variant

- api/kernel/os.hpp
- src/drivers/silent.cpp
- src/drivers/solo5net.cpp
- src/include/kprint
- src/kernel/os.cpp
- src/platform/x86_nano/platform.cpp
- src/platform/x86_pc/os.cpp
- src/platform/x86_pc/serial1.cpp
- src/platform/x86_solo5/kernel_start.cpp
- src/platform/x86_solo5/os.cpp
- src/posix/unistd.cpp
- test/lest_util/os_mock.cpp
Also refactored how solo5 uses stdout, so that (among other things) silent_start works on solo5 platform
> Default stdout now saner

- CMakeLists.txt
- cmake/library.cmake
- cmake/post.service.cmake
- src/arch/x86_64/CMakeLists.txt
- src/arch/x86_64/apic_asm.asm
- src/arch/x86_64/arch_start.asm
- src/arch/x86_64/interrupts.asm
- src/arch/x86_64/ist.cpp
- src/arch/x86_64/tss.hpp
- src/platform/x86_pc/idt.cpp
- src/platform/x86_pc/platform.cpp
- We need to rebuild libc++ and newlib with red-zone enabled
- Test...
> x86_64: Add amd64 IST-support, enable red-zone

- api/net/ws/websocket.hpp
- src/arch/x86_64/ist.cpp
- src/drivers/virtionet.cpp
- src/drivers/virtionet.hpp
- src/kernel/events.cpp
- src/platform/x86_pc/apic_revenant.cpp
- src/platform/x86_pc/apic_revenant.hpp
- src/platform/x86_pc/idt.hpp
- src/platform/x86_pc/platform.cpp
- src/platform/x86_pc/smp.cpp
IST is needed on each core, and the stack should be verified
> x86: Update SMP support for amd64

- CMakeLists.txt
- api/net/dhcp/options.hpp
- api/net/inet.hpp
- api/net/tcp/connection.inc
- api/util/statman.hpp
- cmake/post.service.cmake
- src/kernel/kernel_start.cpp
Unfortunately, 64-bit doesn't work yet, but it does compile
> Enable compiling and running on g++

- api/kernel/os.hpp
- lib/mana/include/mana/components/dashboard/components/cpusage.hpp
- src/drivers/vmxnet3.hpp
- src/kernel/syscalls.cpp
- src/net/tcp/tcp.cpp
- src/platform/x86_pc/apic_revenant.cpp
- src/platform/x86_pc/block.cpp
- src/platform/x86_pc/idt.cpp
- src/platform/x86_pc/os.cpp
- src/platform/x86_solo5/os.cpp
> x86: Various

- api/net/ip4/addr.hpp
- Bug fix operator >
- Added >= and <=
> IP4 addr operator overloading

- README.md
Reworked installation docs. Tested on a brand new macos installation.
> Rework installation docs to match reality

- examples/syslog/README.md
> Fixed typo.

- api/hw/nic.hpp
- examples/acorn/CMakeLists.txt
- examples/acorn/vm.json
- src/drivers/vgaout.cpp
- src/drivers/virtionet.cpp
- src/drivers/vmxnet3.cpp
- src/drivers/vmxnet3.hpp
- src/drivers/vmxnet3_queues.hpp
Also add vmxnet3 by default to acorn
> Implement poll() in network drivers

- api/net/ip4/cidr.hpp
- api/net/ip4/ip4.hpp
- test/CMakeLists.txt
- test/net/unit/cidr.cpp
> IP4 Cidr class

- examples/websocket/service.cpp
- This change fixes the kernel panic when clients
close the websocket.
- This change fixes the kernel panic when a second
client connects to the websocket.
> fix panic on close or 2+ connections

- vmrunner/vmrunner.py
Allows for very nice demos by just creating service.cpp. cmake config is then copied from seed.
> Auto create CMakelist from seed if not present

- api/net/ws/websocket.hpp
- src/net/ws/websocket.cpp
which is a slight performance improvement as well
> websocket: Minor change to simplify append

- api/net/ws/websocket.hpp
- lib/uplink/ws_uplink.cpp
- lib/uplink/ws_uplink.hpp
- src/net/conntrack.cpp
- src/net/nat/napt.cpp
- src/net/ws/websocket.cpp
- test/net/integration/nat/service.cpp
A bit of a rushed implementation... Not fully tested, but at least ping do seem to work.
Uplink still logs, but data is discarded and not sent over websocket if `ws_logging: false` (default is on).
Also added a simple heartbeat if no ping is received during a frequency of 10 secs.
> WebSocket ping pong

- analyze.sh
- cmake/linux.service.cmake
- examples/TCP_perf/linux/CMakeLists.txt
- examples/TCP_perf/linux/run.sh
- examples/TCP_perf/service.cpp
- linux/CMakeLists.txt
- linux/src/CMakeLists.txt
- linux/src/drivers/tap_driver.cpp
- linux/src/os.cpp
- linux/src/profile.cpp
- linux/userspace/CMakeLists.txt
This makes the Linux platform buildable again on dev
> linux: Update linux platform and add support for thinLTO

- CMakeLists.txt
- cmake/post.service.cmake
- cmake/pre.service.cmake
- src/CMakeLists.txt
- src/crt/cxx_abi.cpp
- src/crt/quick_exit.cpp
- src/net/tcp/read_buffer.cpp
- src/net/ws/websocket.cpp
- src/platform/x86_pc/CMakeLists.txt
- src/platform/x86_pc/kernel_start.cpp
- src/platform/x86_pc/serial1.cpp
- It doesn't boot kernel yet, but this should be enough for it to just work once it does
- Maybe MUSL will be the savior
- Adding checks on vptrs requires implementing a hash tree, so disabled for now
- Default OFF
> Add experimental undefined sanitizer support

- linux/src/drivers/usernet.cpp
- linux/src/drivers/usernet.hpp
- src/drivers/virtionet.cpp
- src/drivers/virtionet.hpp
- src/drivers/vmxnet3.cpp
- src/drivers/vmxnet3.hpp
- src/hw/pci_device.cpp
- test/linux/router/CMakeLists.txt
- test/linux/router/async_device.hpp
- test/linux/router/nacl.cpp
- test/linux/router/run.sh
- test/linux/router/service.cpp
- test/linux/tcp/service.cpp
- test/net/integration/websocket/CMakeLists.txt
- test/net/integration/websocket/service.cpp
- test/net/integration/websocket/setup.sh
- test/net/integration/websocket/test.py
- test/net/integration/websocket/vm.json
- test/testrunner.py
and experimental PCI device shutdown for liveupdate
> WebSocket integration test

- api/net/super_stack.hpp
- lib/uplink/CMakeLists.txt
- lib/uplink/config.cpp
- lib/uplink/config.hpp
- lib/uplink/register_plugin.cpp
- lib/uplink/starbase/vm.json
- lib/uplink/ws_uplink.cpp
- lib/uplink/ws_uplink.hpp
- src/net/super_stack.cpp
- test/CMakeLists.txt
- test/lest_util/os_mock.cpp
- test/net/unit/super_stack.cpp
To support #1607. Uplink now respects index (can be either number or MAC).
> Get/create stack by MAC addr in Super_stack

- diskimagebuild/filetree.cpp
> diskbuilder: Fail when unable to enter/read directory, show file errors

- api/arch.hpp
- lib/uplink/ws_uplink.cpp
- lib/uplink/ws_uplink.hpp
- src/hw/msi.cpp
- src/platform/x86_pc/CMakeLists.txt
- src/platform/x86_pc/clocks.cpp
- src/platform/x86_pc/platform.cpp
- src/platform/x86_pc/smbios.cpp
- src/platform/x86_pc/smbios.hpp
- vmrunner/vmrunner.py
- Parse SMBIOS
- Store UUID and report with arch system info call
- Measure time spent during update in uplink
> UUID, SMBIOS parser

- test/net/integration/gateway/nacl.txt
This allows defining Iface index as a MAC address. Solves #1607?
> Update NaCl submodule

- lib/LiveUpdate/CMakeLists.txt
- lib/mender/CMakeLists.txt
- lib/uplink/CMakeLists.txt
- lib/uplink/ws_uplink.cpp
- lib/uplink/ws_uplink.hpp
- src/net/super_stack.cpp
> Uplink fix

- src/hw/nic.cpp
- test/net/integration/router/service.cpp
Also: Make MTU function weak in nic.cpp
> Make router test build again

- examples/demo_service/CMakeLists.txt
- src/platform/x86_pc/acpi.cpp
A solution for #1698 (good enough?)
> Fix to paging in VMware

- cmake/nacl.cmake
(Cleanup that includes renaming cpp_template.py to cpp_transpile_function.py)
> Updating NaCl

- api/util/crc32.hpp
- examples/IRCd/CMakeLists.txt
- examples/IRCd/vm.json
- src/CMakeLists.txt
- src/drivers/e1000.cpp
- src/drivers/vmxnet3.cpp
- src/hw/pci_device.cpp
- src/kernel/elf.cpp
- src/platform/x86_pc/apic_timer.cpp
- src/platform/x86_pc/sanity_checks.cpp
- src/platform/x86_pc/serial1.cpp
- src/util/crc32.cpp
- src/virtio/virtio.cpp
- test/CMakeLists.txt
- test/kernel/integration/LiveUpdate/CMakeLists.txt
- test/kernel/integration/LiveUpdate/test_boot.cpp
- vmbuild/CMakeLists.txt
- vmbuild/elf_syms.cpp
* Also CRC32-C used automatically when SSE4.2 detected
> Avoid VM exits here and there

- lib/uplink/starbase/CMakeLists.txt
- lib/uplink/ws_uplink.cpp
e1000 driver works best for Virtualbox these days.
> starbase: add e1000 driver

- cmake/linux.service.cmake
- examples/demo_linux/run.sh
- linux/src/arch.cpp
- linux/src/main.cpp
- linux/src/os.cpp
- linux/userspace/CMakeLists.txt
- test/linux/router/async_device.hpp
- test/linux/router/nacl.cpp
- test/linux/router/run.sh
- test/linux/router/service.cpp
- test/linux/tcp/service.cpp
... and add some extra options. demo_linux binary is 523kb with LTO.
> Update Linux platform to latest dev

- cmake/cross_compiled_libraries.cmake
- etc/build_llvm.sh
- etc/create_binary_bundle.sh
- src/arch/x86_64/linker.ld
- src/platform/x86_pc/platform.cpp
- src/plugins/CMakeLists.txt
- src/plugins/field_medic/diag.cpp
- src/plugins/field_medic/fieldmedic.cpp
- src/plugins/field_medic/fieldmedic.hpp
- test/kernel/integration/paging/service.cpp
- test/misc/build_examples/test.sh
- test/skipped_tests.json
- vmrunner/vmrunner.py
Use single threaded bundle by default. Libc++ will use thread local storage and emit calls to e.g. posix_key_create etc. when built with threading.
> Single threaded bundle

- vmrunner/vmrunner.py
command line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1733)
> Solo5: Pass kernel arguments so that when solo5 is booted, it can parse it as command line

- .gitignore
Ignore vim swap files (.swp) and CLion project directories (.idea)
> gitignore: Vim and CLion

- test/net/integration/nat/test.py
- test/net/integration/udp/vm.json
- test/net/integration/vlan/test.py
- test/net/integration/websocket/setup.sh
- test/net/integration/websocket/test.py
- test/testrunner.py
- Udp test kept on failing when run together with a lot of other tests.
- Version dependency for websocket python package. There are errors when using the newer version (0.5.1)
> Test stability improvements

- test/net/integration/microLB/setup.sh
- test/net/integration/router/setup.sh
- test/testrunner.py
Also created to test new jenkins build machine.
> Test: Suppress output from apt command in router

- test/misc/build_examples/test.sh
takes 7 secs to test build examples
> Misc : running build examples in parallel

- test/stress/test.py
- test/testrunner.py
Unbufferd python output to improve readability of log files.
> Tests: Make stress test more stable

- test/net/integration/icmp6/CMakeLists.txt
- test/net/integration/icmp6/service.cpp
- test/net/integration/icmp6/setup.sh
- test/net/integration/icmp6/test.py
- test/net/integration/icmp6/vm.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1767)
>  Add test.py to icmp6 integration test. 

- api/common
- api/net/ip6/icmp6.hpp
- api/net/ip6/packet_icmp6.hpp
- api/net/ip6/packet_ip6.hpp
- api/net/packet.hpp
- cmake/post.service.cmake
- src/net/ip6/icmp6.cpp
- src/net/ip6/ip6.cpp
- src/net/ip6/ndp.cpp
- test/net/integration/tcp/linux/CMakeLists.txt
- test/net/integration/tcp/linux/run.sh
- test/net/integration/tcp/service.cpp
Fixes #1814 and fixes an issue where symbols could be completely stripped out when rebuilding
> Lets try this again

- api/arch/x86/cpu.hpp
- api/net/inet
- api/net/inet4
- api/net/tcp/stream.hpp
- api/util/alloc_lstack.hpp
- cmake/post.service.cmake
- lib/LiveUpdate/partition.cpp
- lib/LiveUpdate/storage.cpp
- lib/LiveUpdate/storage.hpp
- linux/src/os.cpp
- seed/service/service.cpp
- src/arch/x86_64/syscall_entry.cpp
- src/musl/common.hpp
- src/platform/x86_pc/apic_iface.hpp
- src/platform/x86_pc/cmos.cpp
- src/platform/x86_pc/x2apic.hpp
- src/platform/x86_pc/xapic.hpp
Enough to build and boot with g++
> Various, building with g++

- api/hw/pci.hpp
- api/hw/pci_device.hpp
- lib/microLB/micro_lb/openssl.cpp
- src/drivers/e1000.cpp
- src/hw/msi.cpp
- src/hw/pci_device.cpp
- src/virtio/virtio.cpp
I dont know of any services that dont run right now, so while the support is brittle, its good enough to run all the tests and examples. Perhaps except STREAM, which is very slow. But maybe its supposed to be slow.
*hashtag road to g++*
> Additional g++ support

- lib/mender/include/mender/inventory.hpp
- lib/uplink/ws_uplink.cpp
- src/util/statman_liu.cpp
- test/kernel/integration/LiveUpdate/test_boot.cpp
- test/stl/integration/exceptions/service.cpp
> catch exception by const reference

- src/net/super_stack.cpp
- test/kernel/integration/fiber/service.cpp
> Refactor emplace back

- src/crt/c_abi.c
- src/kernel/elf.cpp
- src/platform/x86_pc/os.cpp
There is an extra call to sanity checks added because of a crash in acorn
> x86: Protect symbols and strings

- api/net/inet.hpp
- api/net/ip4/arp.hpp
- api/net/ip4/icmp4.hpp
- api/net/ip4/ip4.hpp
- api/net/ip4/packet_arp.hpp
- api/net/ip6/icmp6_common.hpp
- api/net/ip6/mld.hpp
- api/net/ip6/ndp.hpp
- api/net/ip6/packet_icmp6.hpp
- api/net/ip6/packet_mld.hpp
- api/net/ip6/packet_ndp.hpp
- src/CMakeLists.txt
- src/net/inet.cpp
- src/net/ip4/arp.cpp
- src/net/ip4/icmp4.cpp
- src/net/ip4/ip4.cpp
- src/net/ip6/icmp6.cpp
- src/net/ip6/ip6.cpp
- src/net/ip6/mld.cpp
- src/net/ip6/ndp.cpp
- src/net/ip6/packet_mld.cpp
- src/net/ip6/packet_ndp.cpp
- src/plugins/unik.cpp
- test/CMakeLists.txt
MLD changes are very basic and still needs a lot more work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1852)
> Ndp and Mld changes

- src/crt/cxx_abi.cpp
- src/drivers/vmxnet3.cpp
- src/kernel/pci_manager.cpp
- src/platform/x86_pc/CMakeLists.txt
- src/platform/x86_pc/smbios.cpp
- test/linux/tcp/service.cpp
Most cases work well for me now, but there is apparently a lot of spam on delegates for clang-6 / Andreas.
> Undefined-sanitizer support

- Dockerfile
Labels: 🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷🏷
> Dockerfile: Added labels, printing version when building service

- api/net/http/basic_client.hpp
- api/net/http/client_connection.hpp
- examples/http_client/service.cpp
- lib/uplink/ws_uplink.cpp
- src/net/http/basic_client.cpp
- src/net/http/client_connection.cpp
- test/net/integration/http/service.cpp
Default is 0 (can be changed static for *all* clients), or passed as an option.
> HTTP Client follow redirection

- api/arch.hpp
- lib/LiveUpdate/update.cpp
- src/platform/kvm/kvmclock.cpp
- src/platform/kvm/kvmclock.hpp
- src/platform/x86_pc/clocks.cpp
- src/platform/x86_pc/platform.cpp
- src/platform/x86_pc/platform.hpp
- test/lest_util/os_mock.cpp
> Allow x86 platform to deactive devices before live updates

- api/net/s2n/stream.hpp
- cmake/openssl.cmake
- test/linux/fuzz/fuzzy_stream.hpp
- test/linux/s2n/serial.cpp
- test/linux/s2n/serial.hpp
- test/linux/s2n/service.cpp
- WIP, just want jenkins green
- Doesn't work when handshake not complete yet
- Doesn't serialize config yet
- Doesn't serialize TLS stream readq yet
> Basic S2N TLS channel serialization

- CMakeLists.txt
- cmake/cross_compiled_libraries.cmake
- cmake/post.service.cmake
- etc/boot
- etc/scripts/solo5-ifup.sh
- src/drivers/solo5blk.cpp
- src/drivers/solo5net.cpp
- src/drivers/solo5net.hpp
- src/platform/x86_solo5/kernel_start.cpp
- src/platform/x86_solo5/os.cpp
- src/platform/x86_solo5/platform.cpp
- src/platform/x86_solo5/serial1.cpp
- test/misc/solo5-hvt/test.sh
- test_solo5_hvt.sh
- vmrunner/vmrunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/1983)
> solo5: Changes in IncludeOS to point to solo5 0.4.1 release

- .dockerignore
- Dockerfile
Added better labels and cleaned up some unnecessary complexity.
> Dockerfile updates

- code-of-conduct.md
Hi,
A couple of months back we had a discussion about adding a CoC. The discussion didn't really conclude with anything so I thought I'll try to revive it and make sure we end up with something.  Since I'm somewhat familiar with the CoC adopted by Linux I picked it, but IMO anything will do. The main thing is that we have something in place before we need it.
I've put Alfred up as the arbitrator, a role I think he will do well. Hopefully, it won't be much work.
> Suggested code of conduct

- src/CMakeLists.txt
- src/crt/CMakeLists.txt
- src/fs/CMakeLists.txt
- src/hw/CMakeLists.txt
- src/kernel/CMakeLists.txt
- src/kernel/timers.cpp
- src/net/CMakeLists.txt
- src/posix/CMakeLists.txt
- src/util/CMakeLists.txt
- src/virtio/CMakeLists.txt
- test/CMakeLists.txt
- test/fs/unit/unit_fat.cpp
- test/kernel/unit/unit_liveupdate.cpp
Split os src's into multiple cmake virtual targets
Added individual executable tests to the build system and fixed out of tree build of the tests alone. Removed OS list and added os library as shared with the rest..
TODO: 
coverage 
cppcheck
verify nothing is broken in normal os
> Conan test fixes

- api/fs/memdisk.hpp
- api/hw/block_device.hpp
- api/hw/writable_blkdev.hpp
- api/kernel/cpuid.hpp
- api/virtio/virtio.hpp
- lib/LiveUpdate/liveupdate.hpp
- src/drivers/disk_logger.cpp
- src/drivers/ide.cpp
- src/drivers/ide.hpp
- src/drivers/virtioblk.cpp
- src/drivers/virtioblk.hpp
- src/fs/memdisk.cpp
- src/kernel/cpuid.cpp
- src/virtio/virtio_queue.cpp
- test/CMakeLists.txt
- test/hw/unit/usernet.cpp
- test/hw/unit/virtio_queue.cpp
- test/kernel/unit/block.cpp
- test/kernel/unit/cpuid.cpp
- test/kernel/unit/rng.cpp
- test/kernel/unit/unit_events.cpp
- test/lest_util/nic_mock.hpp
- test/lest_util/os_mock.cpp
> More unittests

- test/net/integration/router6/service.cpp
> test: Use correct way to configure network in router6

- CMakeLists.txt
- Jenkinsfile
- conan/README.md
- test/CMakeLists.txt
- test/integration/CMakeLists.txt
- updates to readme
- moved all packages to `conan remote add <REMOTE> https://api.bintray.com/conan/includeos/test-packages `
- fixes to cmakelists for integration test and includeOS
> Conan: Jenkinsfile + few other fixes

- etc/install_dependencies_linux.sh
these are the additional packages i had to install on a fresh Fedora 29 install in order to install successfully
> Add missing dependencies for Fedora

- etc/boot
- vmrunner/vmrunner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hioa-cs/includeos/2070)
> solo5 binary is moved to bin folder from lib

- Jenkinsfile
- Upload works again
- Properly clean workspace before running job. This means we don't have to do `conan remove`.
+ a few other small improvements
> Jenkins cleanup and improvements

- Jenkinsfile
- Build everything with `latest`. Only copy packages to `stable` when building a tag.
- Extended use of functions for build + upload
- Removed CC and CXX.
> Jenkinsfile: Improved flow for latest/stable

- vmrunner/vmrunner.py
This is needed for rdrand/rdseed support on macOS. 
I have not tested if this works with a tap device, it may be limited to slirp.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
> Update vmrunner.py on master to use hvf backend if available

- src/chainload/CMakeLists.txt
- src/chainload/conanfile.py
> chainloader: fixed arch in settings causing issues with test

- api/smp_utils
- api/util/statman.hpp
- src/arch/x86_64/arch_start.asm
- src/util/statman.cpp
For bare metal we still need to deal with the realities of things taking time
> x86: Fix SMP initialization issues

- README.md
Fixing small changes recommended by @AndreasAakesson.
@MagnusS is also making changes to the README, please feel free to pull these fixes to your README changes and close this issue.
> README: grammar fix

- README.md
Restructure README and fix layout (headlines, code formatting). I removed some sections that are now covered in other repos + removed the kernel quick start as that's currently more accurately described in the editable-mode section.
> More readme updates

- Jenkinsfile
- README.md
Also added a Jenkins change. We now always upload to latest, even when we are making a stable package.
> Readme updates 

- cmake/os.cmake
- src/kernel/kernel.cpp
- src/platform/x86_pc/kernel_start.cpp
This was missing from the master->dev port
Note that nothing will run on Jenkins anymore, as you need -cpu host.
> Add for-production mode that can stop the OS when random sources are weak

- api/net/router.hpp
- api/util/statman.hpp
- src/util/statman.cpp
Since Router currently don't have a natural ID they just all have to share the same stats.
> Stats router

- cmake/os.cmake
Still has python2 :( Will create issue to remove this at a later date for nacl.
I'll also create an issue to extract all the NaCl cmake code.
> NaCl: Fix NaCl support

- CMakeLists.txt
- cmake/includeos.cmake
cmake: first atempt at factorizing out a shared cmake between include… os libraries and services
> Isolated the part of the cmake which should be re usable between libraries and maybe also services

- src/kernel/kernel.cpp
Provide a more user friendly termination message.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>
> Update rdrand/rdseed warning message to provide more details

- Jenkinsfile
- README.md
- It was not entering the upload stage when building a tag.
> Pre release fixes

- default.nix
This PR adds the ability to build IncludeOS with [Nix](https://github.com/nixos/nix).
See commits for details.
> Add Nix expression

- src/arch/aarch64/cpu.h
- src/net/checksum.cpp
- src/net/ip6/addr.cpp
> Fix typos in comments

- CMakeLists.txt
- api/posix/fd_map.hpp
- cmake/linux.service.cmake
- cmake/os.cmake
- default.nix
- src/musl/fstatat.cpp
- src/net/dns/record.cpp
- src/net/openssl/client.cpp
- src/net/openssl/server.cpp
- src/net/openssl/tls_stream.cpp
- src/net/tcp/read_buffer.cpp
- src/net/tcp/write_queue.cpp
- src/posix/file_fd.cpp
- test/CMakeLists.txt
Apply the patches from the nix file and remove them. Also install service_name.cpp so we can remove the dependency on the source tree for building a service.
> Remove nix patches

- default.nix
- deps/GSL/default.nix
- deps/botan/default.nix
- deps/http-parser/default.nix
- deps/musl/default.nix
- deps/s2n/default.nix
- deps/uzlib/default.nix
Initial work to create a static nix build. Still has some errors and can't fully build/link includeos yet, but should be useful foundation. Should be followed up by (rebased) #2231 
cc @alfreb
> First steps towards nix static build

- default.nix
- overlay.nix
It's Eurovision Song Contest tonight, so I had to hack a bit in IncludeOS :-)
Commits:
- nix: specify config and overlays when importing nixpkgs
- nix: create a new scope for IncludeOS packages
- ...
> nix: create a new scope for IncludeOS packages

- api/net/router.hpp
- test/kernel/unit/os_test.cpp
- test/net/unit/dhcp.cpp
- test/net/unit/router_test.cpp
Fix more unit tests. See commit messages for details.
> Fix unittests: router_test, dhcp, os_test

- api/util/detail/alloc_pmr.hpp
- test/util/unit/pmr_alloc_test.cpp
Fixes a bug in alloc_pmr reported by valgrind. The allocator would adjust alignment to size(void*), but not size (unless it was less than size(void*)). This resulted in invalid calls to aligned_alloc(). This fixes the bug and adds a test.
I think the correct behaviour here is to always respect the alignment passed to the allocator, as C++ will use the size of the data type as alignment.
> Fix wrong alignment in alloc_pmr

- api/util/logger.hpp
- test/util/unit/logger_test.cpp
The issue was that the new iterator was comparing by value instead of by address.
> Fix logger iterator and logger test

- api/util/fixed_list_alloc.hpp
- test/util/unit/fixed_list_alloc_test.cpp
With this all tests pass for me.
> Fixed_list_alloc test

- README.md
This is a partial README update in preparation for the v0.16 release. It primarily updates the build instructions and removes some outdated references.
For a final version it would also be useful to include more details on how to iterate with cmake in the shell (this is not included here).
> Add nix build instructions to README
